#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Pipeline utility: fill aligned parcel-list fields in Supabase owner tables by land_id/id_list.

Recommended script name:
    8_fill_supabase_owner_list_fields_by_land_id_report_no_arg.py

Purpose:
- Iterates county folders under INPUT_FOLDER.
- Reads CSV/XLSX files generated by the local parcel/owner pipeline.
- Uses the local file's parcel id (`land_id` when present, otherwise `id`) plus `id_list`
  to find the correct existing owner row in Supabase for the same county.
- Updates these aligned array fields in both target tables when values are missing:
      acres_list              numeric[]
      id_list                 integer[]
      market_value_list       numeric[]
      owner_tax_year_list     integer[]
      deed_date_list          date[]
- Does NOT create new owner rows.
- Produces clear terminal progress plus dated HTML/CSV reports.

Why this version exists:
- The prior script matched the input file's `id` to Supabase `unique_id`.
- In the current pipeline, the input `id` is the parcel/land id, while Supabase
  `unique_id` is an internal owner key such as TX-61-3001-1.
- This script matches by Supabase `land_id` and/or overlap with Supabase `id_list`,
  then updates the row's list fields in the correct parcel-id order.

Dependencies:
    pip install pandas python-dotenv supabase openpyxl

Environment:
    SUPABASE_URL
    SUPABASE_SERVICE_ROLE_KEY

Optional environment overrides:
    INPUT_FOLDER
    OWNER_LIST_FIELDS_INPUT_FOLDER
    REPORT_FOLDER
    OWNER_LIST_FIELDS_REPORT_FOLDER
    DRY_RUN=true/false
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from datetime import date, datetime, timezone
from decimal import Decimal, InvalidOperation
from html import escape
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Set, Tuple

import ast
import json
import math
import os
import re
import time
import traceback

import pandas as pd
from dotenv import find_dotenv, load_dotenv

try:
    from supabase import Client, create_client
except Exception:  # pragma: no cover - keeps syntax checks working when supabase is not installed.
    Client = Any  # type: ignore[misc,assignment]
    create_client = None  # type: ignore[assignment]


# =============================================================================
# CONFIG - EDIT THESE VARIABLES, NO CLI ARGUMENTS NEEDED
# =============================================================================

# Folder containing county folders. Each county folder can contain one or more CSV/XLSX files.
DEFAULT_INPUT_FOLDER = Path(
    r"E:\dev\projects\2025\07\15\Texas Real Estate\all_data_counties_category_1_added_test\all_parcels_including_no_acreage\step_8_addresses_enriched"
)

INPUT_FOLDER = Path(
    os.environ.get("OWNER_LIST_FIELDS_INPUT_FOLDER")
    or os.environ.get("INPUT_FOLDER")
    or DEFAULT_INPUT_FOLDER
)

# Supabase tables to update.
COUNTY_TABLE = "county"
TARGET_TABLES = [
    "unique_owner_non_enriched",
    "unique_owner_enriched",
]

# Source columns in local CSV/XLSX files.
# Prefer `land_id` if your pipeline adds it later; current files usually use `id`.
SOURCE_LAND_ID_COLUMN_CANDIDATES = ["land_id", "id"]
SOURCE_ID_LIST_COLUMN = "id_list"
SOURCE_ACRES_LIST_COLUMN = "acres_list"
SOURCE_SCALAR_ACRES_COLUMN = "acres"
SOURCE_FULL_NAME_COLUMN = "full_name"
SOURCE_LANDS_COUNT_COLUMN = "lands_count"

# Fields to fill/update in Supabase.
UPDATE_LIST_FIELDS = [
    "id_list",
    "acres_list",
    "market_value_list",
    "owner_tax_year_list",
    "deed_date_list",
]

VALUE_LIST_FIELDS = [
    "acres_list",
    "market_value_list",
    "owner_tax_year_list",
    "deed_date_list",
]

# Matching behavior.
# A source row can match by exact DB land_id, by source id in DB id_list,
# by DB land_id appearing inside source id_list, or by id_list overlap.
SKIP_AMBIGUOUS_MATCHES = True
MIN_MATCH_SCORE = 1

# Merge behavior.
# False = keep existing non-empty DB values and only fill missing per parcel id.
# True  = source file values overwrite existing DB values when source has non-empty values.
OVERWRITE_EXISTING_VALUES = False

# If true, when source id_list contains ids not present in DB id_list, they are appended.
APPEND_MISSING_INPUT_IDS_TO_EXISTING_ID_LIST = True

# If true, add updated_at to live update payloads.
UPDATE_UPDATED_AT = True

# Dry run toggle. For safety, default is True. Set to False here or set DRY_RUN=false in .env/env.
DRY_RUN_DEFAULT = False
DRY_RUN = str(os.environ.get("DRY_RUN", str(DRY_RUN_DEFAULT))).strip().lower() in {"1", "true", "yes", "y"}

# Optional: limit total prepared source rows per county while testing. Set to None for full run.
TEST_ROW_LIMIT: Optional[int] = None

# Optional: restrict county folders, e.g. ["Hays", "Bastrop"].
SELECTED_COUNTIES: Optional[List[str]] = None

# Batching / retries.
FETCH_COUNTY_ROWS_PAGE_SIZE = 1000
UPDATE_PROGRESS_EVERY = 100
RETRY_ATTEMPTS = 3
RETRY_SLEEP_SEC = 2.0

# Reports. A dated subfolder is created automatically under this base folder.
REPORT_BASE_FOLDER = Path(
    os.environ.get("OWNER_LIST_FIELDS_REPORT_FOLDER")
    or os.environ.get("REPORT_FOLDER")
    or "./reports/supabase_owner_list_fields_update"
)
RUN_DATE_LABEL = datetime.now().strftime("%Y-%m-%d")
RUN_TIME_LABEL = datetime.now().strftime("%H%M%S")
REPORT_FOLDER = REPORT_BASE_FOLDER / RUN_DATE_LABEL
REPORT_HTML_PATH = REPORT_FOLDER / f"supabase_owner_list_fields_update_{RUN_TIME_LABEL}.html"
SUMMARY_CSV_PATH = REPORT_FOLDER / f"supabase_owner_list_fields_update_summary_{RUN_TIME_LABEL}.csv"
SKIPPED_ROWS_CSV_PATH = REPORT_FOLDER / f"supabase_owner_list_fields_update_skipped_rows_{RUN_TIME_LABEL}.csv"
UPDATE_AUDIT_CSV_PATH = REPORT_FOLDER / f"supabase_owner_list_fields_update_audit_{RUN_TIME_LABEL}.csv"

SUPPORTED_SUFFIXES = {".csv", ".xlsx", ".xls", ".xlsm"}
CSV_READ_KWARGS = {
    "dtype": str,
    "keep_default_na": False,
}


# =============================================================================
# DATA MODELS
# =============================================================================

@dataclass
class CountyMeta:
    county_id: int
    county_name: str
    cad_category: Optional[int]


@dataclass
class SourceRecord:
    county_name: str
    source_file: str
    source_row_number: int
    source_land_id: str
    full_name: str
    lands_count: Optional[int]
    id_list: List[int]
    acres_list: List[Optional[float]]
    market_value_list: List[Optional[float]]
    owner_tax_year_list: List[Optional[int]]
    deed_date_list: List[Optional[str]]
    length_mismatch: bool
    padded_fields: str
    trimmed_fields: str
    invalid_id_items: int


@dataclass
class DbOwnerRow:
    table_name: str
    unique_id: str
    county_id: int
    county_name: str
    land_id: str
    full_name: str
    owned_lands: Optional[int]
    acres: Optional[float]
    id_list: List[int]
    acres_list: List[Optional[float]]
    market_value_list: List[Optional[float]]
    owner_tax_year_list: List[Optional[int]]
    deed_date_list: List[Optional[str]]


@dataclass
class MatchResult:
    db_row: DbOwnerRow
    score: int
    method: str
    overlap_count: int
    ambiguous: bool
    ambiguous_unique_ids: str


@dataclass
class ProposedUpdate:
    county_name: str
    table_name: str
    unique_id: str
    source_file: str
    source_row_number: int
    source_land_id: str
    source_id_list_json: str
    db_land_id: str
    db_id_list_json: str
    final_id_list_json: str
    match_method: str
    match_score: int
    overlap_count: int
    fields_changed: str
    ids_added_to_db_list: int
    non_null_acres: int
    non_null_market_values: int
    non_null_owner_tax_years: int
    non_null_deed_dates: int
    payload_fields: Dict[str, Any]


@dataclass
class SkippedRow:
    county_name: str
    table_name: str
    source_file: str
    source_row_number: int
    source_land_id: str
    source_id_list: str
    reason: str
    details: str


@dataclass
class CountyTableReportRow:
    county_name: str
    table_name: str
    files_read: int
    source_rows: int
    prepared_sources: int
    source_rows_missing_land_id: int
    source_rows_without_valid_ids: int
    source_rows_with_length_mismatch: int
    db_rows_fetched: int
    matched_sources: int
    unmatched_sources: int
    ambiguous_sources: int
    no_change_matches: int
    duplicate_update_conflicts: int
    proposed_updates: int
    applied_updates: int
    ids_added_to_db_lists: int
    id_list_updates: int
    acres_list_updates: int
    market_value_updates: int
    owner_tax_year_updates: int
    deed_date_updates: int
    non_null_acres: int
    non_null_market_values: int
    non_null_owner_tax_years: int
    non_null_deed_dates: int
    status: str
    error: Optional[str] = None


# =============================================================================
# LOGGING / BASIC HELPERS
# =============================================================================

def log(message: str) -> None:
    print(message, flush=True)


def utc_now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def now_label() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


def ensure_folder(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def retry_call(fn, *args, **kwargs):
    last_exc: Optional[BaseException] = None
    for attempt in range(1, RETRY_ATTEMPTS + 1):
        try:
            return fn(*args, **kwargs)
        except Exception as exc:
            last_exc = exc
            log(f"[RETRY] Attempt {attempt}/{RETRY_ATTEMPTS} failed: {exc}")
            if attempt < RETRY_ATTEMPTS:
                time.sleep(RETRY_SLEEP_SEC)
    raise last_exc  # type: ignore[misc]


def is_missing(value: Any) -> bool:
    if value is None:
        return True
    try:
        if isinstance(value, float) and math.isnan(value):
            return True
    except Exception:
        pass
    if isinstance(value, str):
        s = value.strip()
        return s == "" or s.lower() in {"nan", "none", "null", "na", "n/a"}
    return False


def clean_scalar_text(value: Any) -> str:
    if is_missing(value):
        return ""
    return str(value).replace("\ufeff", "").strip()


def json_dumps_compact(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"))


# =============================================================================
# SUPABASE
# =============================================================================

def get_supabase_client(env_path: Optional[str] = None) -> Client:
    if create_client is None:
        raise RuntimeError(
            "The 'supabase' package is not installed. Install it with: pip install supabase"
        )

    if env_path is None:
        default_env = Path(__file__).resolve().parent / ".env"
        if default_env.exists():
            load_dotenv(default_env, override=False)
        else:
            load_dotenv(find_dotenv(usecwd=True), override=False)
    else:
        load_dotenv(env_path, override=False)

    url = os.getenv("SUPABASE_URL")
    key = os.getenv("SUPABASE_SERVICE_ROLE_KEY")

    if not url or not key:
        raise RuntimeError(
            "Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY. "
            "Add them to your .env file or environment variables."
        )

    return create_client(url, key)  # type: ignore[misc]


def fetch_county_metadata(client: Client) -> Dict[str, CountyMeta]:
    log("[META] Fetching county metadata from Supabase...")
    resp = retry_call(
        client.table(COUNTY_TABLE)
        .select("county_id, county_name, cad_category")
        .execute
    )
    data = resp.data or []
    out: Dict[str, CountyMeta] = {}
    for row in data:
        county_name = clean_scalar_text(row.get("county_name"))
        if not county_name:
            continue
        out[county_name.lower()] = CountyMeta(
            county_id=int(row["county_id"]),
            county_name=county_name,
            cad_category=row.get("cad_category"),
        )
    log(f"[META] Loaded {len(out):,} county records.")
    return out


def fetch_table_rows_for_county(client: Client, table_name: str, county_id: int) -> List[DbOwnerRow]:
    """Fetch all relevant owner rows for one county and one table."""
    select_cols = ", ".join([
        "unique_id",
        "county_id",
        "county_name",
        "land_id",
        "full_name",
        "owned_lands",
        "acres",
        "id_list",
        "acres_list",
        "market_value_list",
        "owner_tax_year_list",
        "deed_date_list",
    ])

    rows: List[DbOwnerRow] = []
    start = 0
    page = 0
    while True:
        end = start + FETCH_COUNTY_ROWS_PAGE_SIZE - 1
        page += 1
        resp = retry_call(
            client.table(table_name)
            .select(select_cols)
            .eq("county_id", county_id)
            .range(start, end)
            .execute
        )
        data = resp.data or []
        if not data:
            break

        for raw in data:
            rows.append(parse_db_owner_row(table_name, raw))

        log(f"[DB:{table_name}] fetched page {page:,} ({len(rows):,} rows so far)")
        if len(data) < FETCH_COUNTY_ROWS_PAGE_SIZE:
            break
        start += FETCH_COUNTY_ROWS_PAGE_SIZE

    log(f"[DB:{table_name}] total rows fetched for county_id={county_id}: {len(rows):,}")
    return rows


def update_rows_one_by_one(
    client: Client,
    table_name: str,
    county_id: int,
    updates: List[ProposedUpdate],
) -> int:
    """Update existing rows only. This does not upsert and cannot create new owners."""
    if not updates:
        return 0

    affected = 0
    total = len(updates)
    for idx, update in enumerate(updates, start=1):
        if idx == 1 or idx % UPDATE_PROGRESS_EVERY == 0 or idx == total:
            log(f"[DB:{table_name}] {'DRY RUN would update' if DRY_RUN else 'Updating'} {idx:,}/{total:,}")

        if DRY_RUN:
            affected += 1
            continue

        payload = dict(update.payload_fields)
        if UPDATE_UPDATED_AT:
            payload["updated_at"] = utc_now_iso()

        resp = retry_call(
            client.table(table_name)
            .update(payload)
            .eq("county_id", county_id)
            .eq("unique_id", update.unique_id)
            .execute
        )
        data = resp.data or []
        if data:
            affected += len(data)
        else:
            log(f"[WARN] {table_name} unique_id={update.unique_id} returned no updated row.")

    return affected


# =============================================================================
# FILE DISCOVERY / READERS
# =============================================================================

def list_county_folders(input_folder: Path) -> List[Path]:
    if not input_folder.exists():
        raise FileNotFoundError(f"Input folder does not exist: {input_folder}")
    if not input_folder.is_dir():
        raise NotADirectoryError(f"Input path is not a folder: {input_folder}")

    folders = [p for p in input_folder.iterdir() if p.is_dir()]
    if SELECTED_COUNTIES:
        selected = {c.lower() for c in SELECTED_COUNTIES}
        folders = [p for p in folders if p.name.lower() in selected]
    return sorted(folders, key=lambda p: p.name.lower())


def list_data_files(county_folder: Path) -> List[Path]:
    files = [p for p in county_folder.iterdir() if p.is_file() and p.suffix.lower() in SUPPORTED_SUFFIXES]
    files = [p for p in files if not p.name.startswith("~$")]
    return sorted(files, key=lambda p: p.name.lower())


def read_data_file(path: Path) -> pd.DataFrame:
    suffix = path.suffix.lower()
    if suffix == ".csv":
        return pd.read_csv(path, **CSV_READ_KWARGS)
    if suffix in {".xlsx", ".xls", ".xlsm"}:
        return pd.read_excel(path, engine="openpyxl", dtype=str, keep_default_na=False)
    raise ValueError(f"Unsupported file type: {suffix}")


def find_column(df: pd.DataFrame, candidates: Sequence[str]) -> Optional[str]:
    exact = {str(c).strip().lower(): c for c in df.columns}
    for cand in candidates:
        key = cand.strip().lower()
        if key in exact:
            return str(exact[key])
    return None


# =============================================================================
# LIST / VALUE PARSING
# =============================================================================

def parse_list_like_cell(value: Any) -> List[Any]:
    """
    Parses values such as:
      ["123", "456"]
      ['123', '456']
      123,456
      123 | 456
      scalar
    Empty scalar cells return an empty list.
    """
    if value is None:
        return []
    if isinstance(value, (list, tuple)):
        return list(value)
    if isinstance(value, pd.Series):
        return list(value.values)
    if isinstance(value, (datetime, date, pd.Timestamp)):
        return [value]
    if isinstance(value, (int, float, Decimal)):
        if is_missing(value):
            return []
        return [value]

    s = clean_scalar_text(value)
    if not s or s == "[]":
        return []

    if s.startswith("[") and s.endswith("]"):
        try:
            parsed = json.loads(s)
            if isinstance(parsed, list):
                return parsed
        except Exception:
            pass
        try:
            parsed = ast.literal_eval(s)
            if isinstance(parsed, list):
                return parsed
        except Exception:
            pass
        inner = s[1:-1].strip()
        if not inner:
            return []
        return [p.strip().strip("'\"") for p in inner.split(",")]

    if " | " in s:
        return [p.strip() for p in s.split(" | ")]

    if "," in s and not re.search(r"\d{1,2}/\d{1,2}/\d{2,4}", s):
        return [p.strip() for p in s.split(",")]

    return [s]


def parse_numeric_value(value: Any) -> Optional[float]:
    if is_missing(value):
        return None
    if isinstance(value, Decimal):
        return float(value)
    if isinstance(value, (int, float)):
        try:
            if isinstance(value, float) and math.isnan(value):
                return None
            return float(value)
        except Exception:
            return None
    s = clean_scalar_text(value)
    if not s:
        return None
    s = s.strip().strip("'\"")
    s = s.replace("$", "").replace(",", "")
    try:
        return float(Decimal(s))
    except (InvalidOperation, ValueError):
        return None


def parse_integer_value(value: Any) -> Optional[int]:
    if is_missing(value):
        return None
    if isinstance(value, bool):
        return int(value)
    if isinstance(value, int):
        return int(value)
    s = clean_scalar_text(value).strip().strip("'\"")
    if not s:
        return None
    s = s.replace(",", "")
    if re.fullmatch(r"-?\d+", s):
        return int(s)
    if re.fullmatch(r"-?\d+\.0+", s):
        return int(float(s))
    num = parse_numeric_value(s)
    if num is None:
        return None
    try:
        return int(Decimal(str(num)).to_integral_value())
    except Exception:
        return None


def parse_date_value(value: Any) -> Optional[str]:
    """Return ISO date string YYYY-MM-DD, or None."""
    if is_missing(value):
        return None

    if isinstance(value, pd.Timestamp):
        if pd.isna(value):
            return None
        return value.date().isoformat()
    if isinstance(value, datetime):
        return value.date().isoformat()
    if isinstance(value, date):
        return value.isoformat()

    if isinstance(value, (int, float)):
        try:
            if isinstance(value, float) and math.isnan(value):
                return None
            if 20000 <= float(value) <= 80000:
                return pd.to_datetime(value, unit="D", origin="1899-12-30").date().isoformat()
        except Exception:
            pass

    s = clean_scalar_text(value).strip().strip("'\"")
    if not s:
        return None
    s = re.sub(r"T\d{2}:\d{2}:\d{2}(?:\.\d+)?Z?$", "", s)

    for fmt in ("%m/%d/%Y", "%m/%d/%y", "%Y-%m-%d", "%Y/%m/%d", "%m-%d-%Y", "%m-%d-%y"):
        try:
            return datetime.strptime(s, fmt).date().isoformat()
        except ValueError:
            pass

    try:
        parsed = pd.to_datetime(s, errors="coerce")
        if pd.isna(parsed):
            return None
        return parsed.date().isoformat()
    except Exception:
        return None


def parse_typed_list(value: Any, field_name: str) -> List[Any]:
    raw_items = parse_list_like_cell(value)
    parsed: List[Any] = []
    for item in raw_items:
        if field_name in {"acres_list", "market_value_list"}:
            parsed.append(parse_numeric_value(item))
        elif field_name in {"owner_tax_year_list", "id_list"}:
            parsed.append(parse_integer_value(item))
        elif field_name == "deed_date_list":
            parsed.append(parse_date_value(item))
        else:
            parsed.append(None if is_missing(item) else item)
    return parsed


def pad_or_trim(values: List[Any], length: int) -> Tuple[List[Any], bool, bool]:
    padded = False
    trimmed = False
    if length <= 0:
        return values, False, False
    if len(values) < length:
        values = values + [None] * (length - len(values))
        padded = True
    elif len(values) > length:
        values = values[:length]
        trimmed = True
    return values, padded, trimmed


def non_null_count(values: Sequence[Any]) -> int:
    return sum(1 for v in values if v is not None and not is_missing(v))


def normalize_land_id_text(value: Any) -> str:
    s = clean_scalar_text(value)
    if not s:
        return ""
    # Excel sometimes stores IDs as 10522.0.
    if re.fullmatch(r"\d+\.0+", s):
        return str(int(float(s)))
    return s


def normalize_name(value: Any) -> str:
    s = clean_scalar_text(value).lower()
    s = re.sub(r"\s+", " ", s)
    return s.strip()


def extract_ma_hash(value: str) -> str:
    m = re.search(r"\bMA#[A-Z0-9]+\b", clean_scalar_text(value).upper())
    return m.group(0) if m else ""


# =============================================================================
# SOURCE PARSING
# =============================================================================

def get_raw_list_for_source_field(row: pd.Series, field: str, raw_id_len: int) -> List[Any]:
    if field in row.index:
        values = parse_list_like_cell(row.get(field))
    else:
        values = []

    if field == "acres_list" and not values and SOURCE_SCALAR_ACRES_COLUMN in row.index:
        scalar_acres = row.get(SOURCE_SCALAR_ACRES_COLUMN)
        if not is_missing(scalar_acres):
            values = [scalar_acres]

    values, _, _ = pad_or_trim(values, raw_id_len)
    return values


def dedupe_source_lists_by_id(
    ids: List[int],
    acres: List[Optional[float]],
    market: List[Optional[float]],
    tax_year: List[Optional[int]],
    deed_date: List[Optional[str]],
) -> Tuple[List[int], List[Optional[float]], List[Optional[float]], List[Optional[int]], List[Optional[str]]]:
    order: List[int] = []
    data: Dict[int, Dict[str, Any]] = {}
    for idx, parcel_id in enumerate(ids):
        if parcel_id not in data:
            order.append(parcel_id)
            data[parcel_id] = {
                "acres_list": acres[idx] if idx < len(acres) else None,
                "market_value_list": market[idx] if idx < len(market) else None,
                "owner_tax_year_list": tax_year[idx] if idx < len(tax_year) else None,
                "deed_date_list": deed_date[idx] if idx < len(deed_date) else None,
            }
        else:
            # Keep first non-empty value per field.
            if data[parcel_id]["acres_list"] is None and idx < len(acres):
                data[parcel_id]["acres_list"] = acres[idx]
            if data[parcel_id]["market_value_list"] is None and idx < len(market):
                data[parcel_id]["market_value_list"] = market[idx]
            if data[parcel_id]["owner_tax_year_list"] is None and idx < len(tax_year):
                data[parcel_id]["owner_tax_year_list"] = tax_year[idx]
            if data[parcel_id]["deed_date_list"] is None and idx < len(deed_date):
                data[parcel_id]["deed_date_list"] = deed_date[idx]

    return (
        order,
        [data[i]["acres_list"] for i in order],
        [data[i]["market_value_list"] for i in order],
        [data[i]["owner_tax_year_list"] for i in order],
        [data[i]["deed_date_list"] for i in order],
    )


def prepare_source_record(
    row: pd.Series,
    land_id_col: str,
    county_name: str,
    source_file: str,
    source_row_number: int,
) -> Tuple[Optional[SourceRecord], Optional[SkippedRow]]:
    source_land_id = normalize_land_id_text(row.get(land_id_col))
    if not source_land_id:
        return None, SkippedRow(
            county_name=county_name,
            table_name="source_file",
            source_file=source_file,
            source_row_number=source_row_number,
            source_land_id="",
            source_id_list="",
            reason="missing_source_land_id",
            details=f"Expected one of {SOURCE_LAND_ID_COLUMN_CANDIDATES}; using column {land_id_col}.",
        )

    raw_id_items = parse_list_like_cell(row.get(SOURCE_ID_LIST_COLUMN)) if SOURCE_ID_LIST_COLUMN in row.index else []
    if not raw_id_items:
        raw_id_items = [source_land_id]

    raw_id_len = len(raw_id_items)
    valid_positions: List[int] = []
    parsed_ids: List[int] = []
    invalid_id_items = 0
    for pos, item in enumerate(raw_id_items):
        parsed_id = parse_integer_value(item)
        if parsed_id is None:
            invalid_id_items += 1
            continue
        valid_positions.append(pos)
        parsed_ids.append(parsed_id)

    if not parsed_ids:
        source_as_int = parse_integer_value(source_land_id)
        if source_as_int is not None:
            raw_id_items = [source_land_id]
            raw_id_len = 1
            valid_positions = [0]
            parsed_ids = [source_as_int]
        else:
            return None, SkippedRow(
                county_name=county_name,
                table_name="source_file",
                source_file=source_file,
                source_row_number=source_row_number,
                source_land_id=source_land_id,
                source_id_list=json_dumps_compact(raw_id_items),
                reason="no_valid_parcel_ids",
                details="Neither id_list nor source land_id contained a valid integer parcel id.",
            )

    padded_fields: List[str] = []
    trimmed_fields: List[str] = []
    length_mismatch = invalid_id_items > 0

    field_raw: Dict[str, List[Any]] = {}
    for field in VALUE_LIST_FIELDS:
        raw_values = get_raw_list_for_source_field(row, field, raw_id_len)
        original_len = len(parse_list_like_cell(row.get(field))) if field in row.index else 0
        if field == "acres_list" and original_len == 0 and SOURCE_SCALAR_ACRES_COLUMN in row.index and not is_missing(row.get(SOURCE_SCALAR_ACRES_COLUMN)):
            original_len = 1
        if original_len and original_len != raw_id_len:
            length_mismatch = True
            if original_len < raw_id_len:
                padded_fields.append(field)
            elif original_len > raw_id_len:
                trimmed_fields.append(field)
        field_raw[field] = raw_values

    acres = [parse_numeric_value(field_raw["acres_list"][pos]) for pos in valid_positions]
    market = [parse_numeric_value(field_raw["market_value_list"][pos]) for pos in valid_positions]
    tax_year = [parse_integer_value(field_raw["owner_tax_year_list"][pos]) for pos in valid_positions]
    deed_date = [parse_date_value(field_raw["deed_date_list"][pos]) for pos in valid_positions]

    parsed_ids, acres, market, tax_year, deed_date = dedupe_source_lists_by_id(
        parsed_ids, acres, market, tax_year, deed_date
    )

    full_name = clean_scalar_text(row.get(SOURCE_FULL_NAME_COLUMN)) if SOURCE_FULL_NAME_COLUMN in row.index else ""
    lands_count = parse_integer_value(row.get(SOURCE_LANDS_COUNT_COLUMN)) if SOURCE_LANDS_COUNT_COLUMN in row.index else None

    return SourceRecord(
        county_name=county_name,
        source_file=source_file,
        source_row_number=source_row_number,
        source_land_id=source_land_id,
        full_name=full_name,
        lands_count=lands_count,
        id_list=parsed_ids,
        acres_list=acres,
        market_value_list=market,
        owner_tax_year_list=tax_year,
        deed_date_list=deed_date,
        length_mismatch=length_mismatch,
        padded_fields=", ".join(sorted(set(padded_fields))),
        trimmed_fields=", ".join(sorted(set(trimmed_fields))),
        invalid_id_items=invalid_id_items,
    ), None


def read_and_prepare_county_sources(
    county_folder: Path,
    county_name: str,
) -> Tuple[List[SourceRecord], List[SkippedRow], Dict[str, int]]:
    files = list_data_files(county_folder)
    stats = {
        "files_read": 0,
        "source_rows": 0,
        "prepared_sources": 0,
        "source_rows_missing_land_id": 0,
        "source_rows_without_valid_ids": 0,
        "source_rows_with_length_mismatch": 0,
    }
    sources: List[SourceRecord] = []
    skipped: List[SkippedRow] = []

    if not files:
        log(f"[WARN] No data files found in county folder: {county_folder}")
        return sources, skipped, stats

    for file_path in files:
        log(f"[FILE] Reading {county_name}: {file_path.name}")
        df = read_data_file(file_path)
        stats["files_read"] += 1
        stats["source_rows"] += len(df)

        land_id_col = find_column(df, SOURCE_LAND_ID_COLUMN_CANDIDATES)
        if not land_id_col:
            log(f"[WARN] {file_path.name}: missing source land id column. Expected {SOURCE_LAND_ID_COLUMN_CANDIDATES}")
            for row_number in range(2, len(df) + 2):
                skipped.append(SkippedRow(
                    county_name=county_name,
                    table_name="source_file",
                    source_file=file_path.name,
                    source_row_number=row_number,
                    source_land_id="",
                    source_id_list="",
                    reason="missing_source_land_id_column",
                    details=f"Expected one of {SOURCE_LAND_ID_COLUMN_CANDIDATES}",
                ))
            stats["source_rows_missing_land_id"] += len(df)
            continue

        missing_optional = [c for c in UPDATE_LIST_FIELDS if c not in df.columns]
        if missing_optional:
            log(f"[WARN] {file_path.name}: missing optional update columns: {missing_optional}")

        for idx, row in df.iterrows():
            source_row_number = int(idx) + 2
            source, skip = prepare_source_record(
                row=row,
                land_id_col=land_id_col,
                county_name=county_name,
                source_file=file_path.name,
                source_row_number=source_row_number,
            )
            if skip is not None:
                skipped.append(skip)
                if skip.reason in {"missing_source_land_id", "missing_source_land_id_column"}:
                    stats["source_rows_missing_land_id"] += 1
                elif skip.reason == "no_valid_parcel_ids":
                    stats["source_rows_without_valid_ids"] += 1
                continue
            if source is None:
                continue

            sources.append(source)
            stats["prepared_sources"] += 1
            stats["source_rows_with_length_mismatch"] += int(source.length_mismatch)

            if TEST_ROW_LIMIT is not None and len(sources) >= TEST_ROW_LIMIT:
                log(f"[TEST] Reached TEST_ROW_LIMIT={TEST_ROW_LIMIT:,} while reading {county_name}.")
                return sources, skipped, stats

    return sources, skipped, stats


# =============================================================================
# DATABASE ROW PARSING / INDEXING
# =============================================================================

def parse_db_owner_row(table_name: str, raw: Dict[str, Any]) -> DbOwnerRow:
    return DbOwnerRow(
        table_name=table_name,
        unique_id=clean_scalar_text(raw.get("unique_id")),
        county_id=int(raw.get("county_id") or 0),
        county_name=clean_scalar_text(raw.get("county_name")),
        land_id=normalize_land_id_text(raw.get("land_id")),
        full_name=clean_scalar_text(raw.get("full_name")),
        owned_lands=parse_integer_value(raw.get("owned_lands")),
        acres=parse_numeric_value(raw.get("acres")),
        id_list=[i for i in parse_typed_list(raw.get("id_list"), "id_list") if i is not None],
        acres_list=parse_typed_list(raw.get("acres_list"), "acres_list"),
        market_value_list=parse_typed_list(raw.get("market_value_list"), "market_value_list"),
        owner_tax_year_list=parse_typed_list(raw.get("owner_tax_year_list"), "owner_tax_year_list"),
        deed_date_list=parse_typed_list(raw.get("deed_date_list"), "deed_date_list"),
    )


def build_db_indices(db_rows: List[DbOwnerRow]) -> Tuple[Dict[str, List[DbOwnerRow]], Dict[int, List[DbOwnerRow]]]:
    by_land_id: Dict[str, List[DbOwnerRow]] = {}
    by_parcel_id: Dict[int, List[DbOwnerRow]] = {}

    for row in db_rows:
        if row.land_id:
            by_land_id.setdefault(row.land_id, []).append(row)
            land_id_int = parse_integer_value(row.land_id)
            if land_id_int is not None and not row.id_list:
                # If id_list is not populated yet, still allow matching by the row land_id.
                by_parcel_id.setdefault(land_id_int, []).append(row)

        for parcel_id in row.id_list:
            by_parcel_id.setdefault(parcel_id, []).append(row)

    return by_land_id, by_parcel_id


# =============================================================================
# MATCHING
# =============================================================================

def name_score(source_name: str, db_name: str) -> int:
    src = normalize_name(source_name)
    db = normalize_name(db_name)
    if not src or not db:
        return 0
    if src == db:
        return 30

    src_hash = extract_ma_hash(source_name)
    db_hash = extract_ma_hash(db_name)
    if src_hash and db_hash and src_hash == db_hash:
        return 25

    # Small bonus when the primary owner token is clearly contained.
    src_primary = src.split("|")[-1].strip() if "|" in src else src
    src_primary = re.sub(r"\(\+\d+\s+others?\)", "", src_primary).strip()
    if src_primary and (src_primary in db or db in src_primary):
        return 10
    return 0


def score_candidate(source: SourceRecord, db_row: DbOwnerRow) -> Tuple[int, str, int]:
    methods: List[str] = []
    score = 0

    source_land_id = source.source_land_id
    source_land_id_int = parse_integer_value(source_land_id)
    source_ids = set(source.id_list)
    db_ids = set(db_row.id_list)
    db_land_id_int = parse_integer_value(db_row.land_id)

    if source_land_id and db_row.land_id and source_land_id == db_row.land_id:
        score += 10000
        methods.append("exact_land_id")

    overlap = len(source_ids.intersection(db_ids))
    if overlap:
        score += 100 * overlap
        methods.append(f"id_list_overlap:{overlap}")

    if source_land_id_int is not None and source_land_id_int in db_ids:
        score += 250
        methods.append("source_id_in_db_id_list")

    if db_land_id_int is not None and db_land_id_int in source_ids:
        score += 150
        methods.append("db_land_id_in_source_id_list")

    ns = name_score(source.full_name, db_row.full_name)
    if ns:
        score += ns
        methods.append("name_match")

    source_count = len(source.id_list)
    db_count = len(db_row.id_list) or db_row.owned_lands or 0
    if source_count and db_count:
        if source_count == db_count:
            score += 25
            methods.append("same_list_length")
        else:
            score -= min(abs(source_count - db_count), 25)

    if source.lands_count is not None and db_row.owned_lands is not None:
        if source.lands_count == db_row.owned_lands:
            score += 10
            methods.append("same_owned_lands")

    return score, "+".join(methods) if methods else "no_match", overlap


def find_best_match(
    source: SourceRecord,
    by_land_id: Dict[str, List[DbOwnerRow]],
    by_parcel_id: Dict[int, List[DbOwnerRow]],
) -> Optional[MatchResult]:
    candidates: Dict[str, DbOwnerRow] = {}

    for row in by_land_id.get(source.source_land_id, []):
        candidates[row.unique_id] = row

    for parcel_id in source.id_list:
        for row in by_parcel_id.get(parcel_id, []):
            candidates[row.unique_id] = row

    if not candidates:
        return None

    scored: List[Tuple[int, str, int, DbOwnerRow]] = []
    for row in candidates.values():
        score, method, overlap = score_candidate(source, row)
        if score >= MIN_MATCH_SCORE:
            scored.append((score, method, overlap, row))

    if not scored:
        return None

    scored.sort(key=lambda x: (x[0], x[2], x[3].unique_id), reverse=True)
    best_score, best_method, best_overlap, best_row = scored[0]

    tied = [item for item in scored if item[0] == best_score and item[2] == best_overlap]
    ambiguous = len(tied) > 1
    ambiguous_ids = ", ".join(sorted(t[3].unique_id for t in tied)) if ambiguous else ""

    return MatchResult(
        db_row=best_row,
        score=best_score,
        method=best_method,
        overlap_count=best_overlap,
        ambiguous=ambiguous,
        ambiguous_unique_ids=ambiguous_ids,
    )


# =============================================================================
# MERGING / PAYLOAD BUILDING
# =============================================================================

def value_is_present(value: Any) -> bool:
    return value is not None and not is_missing(value)


def normalize_existing_list_for_ids(values: List[Any], ids: List[int]) -> Dict[int, Any]:
    out: Dict[int, Any] = {}
    values, _, _ = pad_or_trim(list(values), len(ids))
    for idx, parcel_id in enumerate(ids):
        if parcel_id not in out:
            out[parcel_id] = values[idx] if idx < len(values) else None
        elif not value_is_present(out[parcel_id]) and idx < len(values):
            out[parcel_id] = values[idx]
    return out


def source_mapping(source: SourceRecord, field: str) -> Dict[int, Any]:
    values = getattr(source, field)
    values, _, _ = pad_or_trim(list(values), len(source.id_list))
    out: Dict[int, Any] = {}
    for idx, parcel_id in enumerate(source.id_list):
        val = values[idx] if idx < len(values) else None
        if parcel_id not in out:
            out[parcel_id] = val
        elif not value_is_present(out[parcel_id]) and value_is_present(val):
            out[parcel_id] = val
    return out


def numeric_equal(a: Any, b: Any) -> bool:
    if not value_is_present(a) and not value_is_present(b):
        return True
    if not value_is_present(a) or not value_is_present(b):
        return False
    try:
        return abs(float(a) - float(b)) < 1e-9
    except Exception:
        return clean_scalar_text(a) == clean_scalar_text(b)


def values_equal(field: str, a: Any, b: Any) -> bool:
    if field in {"acres_list", "market_value_list"}:
        return numeric_equal(a, b)
    if field == "owner_tax_year_list":
        return parse_integer_value(a) == parse_integer_value(b)
    if field == "deed_date_list":
        return parse_date_value(a) == parse_date_value(b)
    return a == b


def lists_equal(field: str, a: List[Any], b: List[Any]) -> bool:
    if len(a) != len(b):
        return False
    return all(values_equal(field, x, y) for x, y in zip(a, b))


def final_value(existing_value: Any, source_value: Any) -> Any:
    if OVERWRITE_EXISTING_VALUES:
        return source_value if value_is_present(source_value) else existing_value
    return existing_value if value_is_present(existing_value) else source_value


def build_update_payload(source: SourceRecord, db_row: DbOwnerRow, match: MatchResult) -> Optional[ProposedUpdate]:
    db_ids = list(db_row.id_list)
    source_ids = list(source.id_list)

    final_ids: List[int] = []
    seen: Set[int] = set()

    for parcel_id in db_ids:
        if parcel_id not in seen:
            final_ids.append(parcel_id)
            seen.add(parcel_id)

    if APPEND_MISSING_INPUT_IDS_TO_EXISTING_ID_LIST:
        for parcel_id in source_ids:
            if parcel_id not in seen:
                final_ids.append(parcel_id)
                seen.add(parcel_id)

    if not final_ids:
        final_ids = source_ids

    if not final_ids:
        return None

    payload: Dict[str, Any] = {}
    fields_changed: List[str] = []

    if db_ids != final_ids:
        payload["id_list"] = final_ids
        fields_changed.append("id_list")

    ids_added = len([i for i in source_ids if i not in set(db_ids)])

    existing_maps: Dict[str, Dict[int, Any]] = {
        "acres_list": normalize_existing_list_for_ids(db_row.acres_list, db_ids),
        "market_value_list": normalize_existing_list_for_ids(db_row.market_value_list, db_ids),
        "owner_tax_year_list": normalize_existing_list_for_ids(db_row.owner_tax_year_list, db_ids),
        "deed_date_list": normalize_existing_list_for_ids(db_row.deed_date_list, db_ids),
    }

    # If DB id_list is empty but DB land_id/acres exists, let acres participate in the merge.
    db_land_id_int = parse_integer_value(db_row.land_id)
    if not db_ids and db_land_id_int is not None and db_row.acres is not None:
        existing_maps["acres_list"][db_land_id_int] = db_row.acres

    source_maps: Dict[str, Dict[int, Any]] = {
        field: source_mapping(source, field)
        for field in VALUE_LIST_FIELDS
    }

    final_lists: Dict[str, List[Any]] = {}
    for field in VALUE_LIST_FIELDS:
        values: List[Any] = []
        for parcel_id in final_ids:
            existing_val = existing_maps[field].get(parcel_id)
            source_val = source_maps[field].get(parcel_id)
            values.append(final_value(existing_val, source_val))
        final_lists[field] = values

        # Do not write completely empty optional value arrays, unless existing had values and list shape changed.
        existing_aligned = [existing_maps[field].get(parcel_id) for parcel_id in final_ids]
        has_any_value = any(value_is_present(v) for v in values)
        existing_has_any_value = any(value_is_present(v) for v in existing_aligned)

        if has_any_value and not lists_equal(field, existing_aligned, values):
            payload[field] = values
            fields_changed.append(field)
        elif field == "acres_list" and not existing_has_any_value and has_any_value:
            payload[field] = values
            fields_changed.append(field)

    if not payload:
        return None

    return ProposedUpdate(
        county_name=source.county_name,
        table_name=db_row.table_name,
        unique_id=db_row.unique_id,
        source_file=source.source_file,
        source_row_number=source.source_row_number,
        source_land_id=source.source_land_id,
        source_id_list_json=json_dumps_compact(source.id_list),
        db_land_id=db_row.land_id,
        db_id_list_json=json_dumps_compact(db_row.id_list),
        final_id_list_json=json_dumps_compact(final_ids),
        match_method=match.method,
        match_score=match.score,
        overlap_count=match.overlap_count,
        fields_changed=", ".join(fields_changed),
        ids_added_to_db_list=ids_added,
        non_null_acres=non_null_count(final_lists["acres_list"]),
        non_null_market_values=non_null_count(final_lists["market_value_list"]),
        non_null_owner_tax_years=non_null_count(final_lists["owner_tax_year_list"]),
        non_null_deed_dates=non_null_count(final_lists["deed_date_list"]),
        payload_fields=payload,
    )


def resolve_duplicate_updates(updates: List[ProposedUpdate]) -> Tuple[List[ProposedUpdate], int, List[SkippedRow]]:
    """If multiple source rows target the same DB unique_id, keep the strongest one."""
    by_uid: Dict[str, List[ProposedUpdate]] = {}
    for upd in updates:
        by_uid.setdefault(upd.unique_id, []).append(upd)

    resolved: List[ProposedUpdate] = []
    skipped: List[SkippedRow] = []
    duplicate_conflicts = 0

    for uid, group in by_uid.items():
        if len(group) == 1:
            resolved.append(group[0])
            continue
        duplicate_conflicts += len(group) - 1
        group.sort(
            key=lambda u: (
                u.match_score,
                u.overlap_count,
                len((u.fields_changed or "").split(",")),
                u.source_row_number,
            ),
            reverse=True,
        )
        winner = group[0]
        resolved.append(winner)
        for loser in group[1:]:
            skipped.append(SkippedRow(
                county_name=loser.county_name,
                table_name=loser.table_name,
                source_file=loser.source_file,
                source_row_number=loser.source_row_number,
                source_land_id=loser.source_land_id,
                source_id_list=loser.source_id_list_json,
                reason="duplicate_update_same_unique_id_lost",
                details=f"unique_id={uid}; kept source row {winner.source_row_number} with score {winner.match_score}.",
            ))

    return resolved, duplicate_conflicts, skipped


# =============================================================================
# TABLE PROCESSING
# =============================================================================

def process_table_for_county(
    client: Client,
    county_meta: CountyMeta,
    county_name: str,
    table_name: str,
    sources: List[SourceRecord],
    source_skips: List[SkippedRow],
    source_stats: Dict[str, int],
) -> Tuple[CountyTableReportRow, List[SkippedRow], List[ProposedUpdate]]:
    db_rows = fetch_table_rows_for_county(client, table_name, county_meta.county_id)
    by_land_id, by_parcel_id = build_db_indices(db_rows)

    table_skips: List[SkippedRow] = []
    proposed_updates: List[ProposedUpdate] = []
    matched_sources = 0
    unmatched_sources = 0
    ambiguous_sources = 0
    no_change_matches = 0

    log(f"[MATCH:{table_name}] Matching {len(sources):,} source row(s) for {county_name}...")
    for idx, source in enumerate(sources, start=1):
        if idx == 1 or idx % 500 == 0 or idx == len(sources):
            log(f"[MATCH:{table_name}] {idx:,}/{len(sources):,}")

        match = find_best_match(source, by_land_id, by_parcel_id)
        if match is None:
            unmatched_sources += 1
            table_skips.append(SkippedRow(
                county_name=county_name,
                table_name=table_name,
                source_file=source.source_file,
                source_row_number=source.source_row_number,
                source_land_id=source.source_land_id,
                source_id_list=json_dumps_compact(source.id_list),
                reason="no_matching_db_row",
                details="No DB row matched by land_id or id_list overlap for this county/table.",
            ))
            continue

        if match.ambiguous and SKIP_AMBIGUOUS_MATCHES:
            ambiguous_sources += 1
            table_skips.append(SkippedRow(
                county_name=county_name,
                table_name=table_name,
                source_file=source.source_file,
                source_row_number=source.source_row_number,
                source_land_id=source.source_land_id,
                source_id_list=json_dumps_compact(source.id_list),
                reason="ambiguous_match_skipped",
                details=f"score={match.score}; candidates={match.ambiguous_unique_ids}",
            ))
            continue

        matched_sources += 1
        update = build_update_payload(source, match.db_row, match)
        if update is None:
            no_change_matches += 1
            continue
        proposed_updates.append(update)

    proposed_updates, duplicate_conflicts, duplicate_skips = resolve_duplicate_updates(proposed_updates)
    table_skips.extend(duplicate_skips)

    log(
        f"[MATCH:{table_name}] matched={matched_sources:,} unmatched={unmatched_sources:,} "
        f"ambiguous={ambiguous_sources:,} no_change={no_change_matches:,} updates={len(proposed_updates):,}"
    )

    applied = update_rows_one_by_one(client, table_name, county_meta.county_id, proposed_updates)

    def count_field_updates(field: str) -> int:
        return sum(1 for u in proposed_updates if field in [f.strip() for f in u.fields_changed.split(",")])

    report = CountyTableReportRow(
        county_name=county_name,
        table_name=table_name,
        files_read=source_stats.get("files_read", 0),
        source_rows=source_stats.get("source_rows", 0),
        prepared_sources=len(sources),
        source_rows_missing_land_id=source_stats.get("source_rows_missing_land_id", 0),
        source_rows_without_valid_ids=source_stats.get("source_rows_without_valid_ids", 0),
        source_rows_with_length_mismatch=source_stats.get("source_rows_with_length_mismatch", 0),
        db_rows_fetched=len(db_rows),
        matched_sources=matched_sources,
        unmatched_sources=unmatched_sources,
        ambiguous_sources=ambiguous_sources,
        no_change_matches=no_change_matches,
        duplicate_update_conflicts=duplicate_conflicts,
        proposed_updates=len(proposed_updates),
        applied_updates=applied,
        ids_added_to_db_lists=sum(u.ids_added_to_db_list for u in proposed_updates),
        id_list_updates=count_field_updates("id_list"),
        acres_list_updates=count_field_updates("acres_list"),
        market_value_updates=count_field_updates("market_value_list"),
        owner_tax_year_updates=count_field_updates("owner_tax_year_list"),
        deed_date_updates=count_field_updates("deed_date_list"),
        non_null_acres=sum(u.non_null_acres for u in proposed_updates),
        non_null_market_values=sum(u.non_null_market_values for u in proposed_updates),
        non_null_owner_tax_years=sum(u.non_null_owner_tax_years for u in proposed_updates),
        non_null_deed_dates=sum(u.non_null_deed_dates for u in proposed_updates),
        status="ok",
    )

    return report, table_skips, proposed_updates


# =============================================================================
# REPORTING
# =============================================================================

def write_csv_reports(
    county_table_reports: List[CountyTableReportRow],
    skipped_rows: List[SkippedRow],
    proposed_updates: List[ProposedUpdate],
) -> None:
    ensure_folder(REPORT_FOLDER)

    pd.DataFrame([asdict(r) for r in county_table_reports]).to_csv(SUMMARY_CSV_PATH, index=False)
    log(f"[REPORT] Summary CSV written: {SUMMARY_CSV_PATH}")

    if skipped_rows:
        pd.DataFrame([asdict(r) for r in skipped_rows]).to_csv(SKIPPED_ROWS_CSV_PATH, index=False)
    else:
        pd.DataFrame(columns=[f.name for f in SkippedRow.__dataclass_fields__.values()]).to_csv(SKIPPED_ROWS_CSV_PATH, index=False)
    log(f"[REPORT] Skipped-row audit CSV written: {SKIPPED_ROWS_CSV_PATH}")

    audit_rows = []
    for u in proposed_updates:
        row = asdict(u)
        # Keep audit CSV readable; payload can be large.
        row["payload_fields"] = json_dumps_compact(u.payload_fields)
        audit_rows.append(row)
    pd.DataFrame(audit_rows).to_csv(UPDATE_AUDIT_CSV_PATH, index=False)
    log(f"[REPORT] Update audit CSV written: {UPDATE_AUDIT_CSV_PATH}")


def generate_html_report(
    county_table_reports: List[CountyTableReportRow],
    skipped_rows: List[SkippedRow],
    proposed_updates: List[ProposedUpdate],
    started_at: datetime,
    ended_at: datetime,
) -> None:
    ensure_folder(REPORT_HTML_PATH.parent)

    totals = {
        "counties": len(set(r.county_name for r in county_table_reports)),
        "table_runs": len(county_table_reports),
        "source_rows": max(sum(r.source_rows for r in county_table_reports if r.table_name == TARGET_TABLES[0]), 0),
        "prepared_sources": max(sum(r.prepared_sources for r in county_table_reports if r.table_name == TARGET_TABLES[0]), 0),
        "db_rows_fetched": sum(r.db_rows_fetched for r in county_table_reports),
        "matched_sources": sum(r.matched_sources for r in county_table_reports),
        "proposed_updates": sum(r.proposed_updates for r in county_table_reports),
        "applied_updates": sum(r.applied_updates for r in county_table_reports),
        "unmatched_sources": sum(r.unmatched_sources for r in county_table_reports),
        "ambiguous_sources": sum(r.ambiguous_sources for r in county_table_reports),
        "no_change_matches": sum(r.no_change_matches for r in county_table_reports),
        "market_values": sum(r.non_null_market_values for r in county_table_reports),
        "tax_years": sum(r.non_null_owner_tax_years for r in county_table_reports),
        "deed_dates": sum(r.non_null_deed_dates for r in county_table_reports),
    }

    rows_html_parts = []
    for r in county_table_reports:
        status_class = "ok" if r.status == "ok" else "warn"
        error_html = f"<code>{escape(r.error or '')}</code>" if r.error else ""
        rows_html_parts.append(f"""
        <tr>
          <td>{escape(r.county_name)}</td>
          <td>{escape(r.table_name)}</td>
          <td class="num">{r.files_read:,}</td>
          <td class="num">{r.source_rows:,}</td>
          <td class="num">{r.prepared_sources:,}</td>
          <td class="num">{r.db_rows_fetched:,}</td>
          <td class="num">{r.matched_sources:,}</td>
          <td class="num warn-text">{r.unmatched_sources:,}</td>
          <td class="num warn-text">{r.ambiguous_sources:,}</td>
          <td class="num">{r.no_change_matches:,}</td>
          <td class="num good">{r.proposed_updates:,}</td>
          <td class="num good">{r.applied_updates:,}</td>
          <td class="num">{r.id_list_updates:,}</td>
          <td class="num">{r.acres_list_updates:,}</td>
          <td class="num">{r.market_value_updates:,}</td>
          <td class="num">{r.owner_tax_year_updates:,}</td>
          <td class="num">{r.deed_date_updates:,}</td>
          <td><span class="badge {status_class}">{escape(r.status)}</span></td>
          <td>{error_html}</td>
        </tr>
        """)

    if not rows_html_parts:
        rows_html = "<tr><td colspan='19' class='empty'>No counties processed.</td></tr>"
    else:
        rows_html = "\n".join(rows_html_parts)

    skip_reason_counts: Dict[str, int] = {}
    for row in skipped_rows:
        skip_reason_counts[row.reason] = skip_reason_counts.get(row.reason, 0) + 1
    skip_html = "".join(
        f"<tr><td>{escape(reason)}</td><td class='num'>{count:,}</td></tr>"
        for reason, count in sorted(skip_reason_counts.items(), key=lambda x: (-x[1], x[0]))
    ) or "<tr><td colspan='2' class='empty'>No skipped rows.</td></tr>"

    field_change_counts: Dict[str, int] = {field: 0 for field in UPDATE_LIST_FIELDS}
    for upd in proposed_updates:
        for field in [f.strip() for f in upd.fields_changed.split(",") if f.strip()]:
            field_change_counts[field] = field_change_counts.get(field, 0) + 1
    field_html = "".join(
        f"<tr><td>{escape(field)}</td><td class='num'>{count:,}</td></tr>"
        for field, count in field_change_counts.items()
    )

    run_seconds = (ended_at - started_at).total_seconds()
    dry_run_note = "DRY RUN - no database rows were changed" if DRY_RUN else "LIVE UPDATE - matching Supabase rows were updated"

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Supabase Owner List Fields Update Report</title>
<style>
  body {{
    background-color: #f0f0f0;
    font-family: Arial, sans-serif;
    padding: 20px;
    color: #222;
  }}
  h1, h2 {{ color: #333; }}
  .summary-box {{
    background: #fff;
    border-radius: 8px;
    padding: 16px;
    margin-bottom: 18px;
    box-shadow: 0 1px 3px rgba(0,0,0,0.12);
    font-size: 14px;
  }}
  .cards {{
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(210px, 1fr));
    gap: 12px;
    margin: 14px 0;
  }}
  .card {{
    background: #fff;
    border-radius: 8px;
    padding: 14px;
    box-shadow: 0 1px 3px rgba(0,0,0,0.12);
  }}
  .card .label {{
    color: #666;
    font-size: 12px;
    text-transform: uppercase;
    letter-spacing: .03em;
  }}
  .card .value {{
    margin-top: 6px;
    font-size: 24px;
    font-weight: bold;
  }}
  table {{
    width: 100%;
    border-collapse: collapse;
    background: #fff;
    box-shadow: 0 1px 3px rgba(0,0,0,0.12);
    margin-bottom: 20px;
  }}
  th, td {{
    padding: 8px 10px;
    border-bottom: 1px solid #e2e2e2;
    font-size: 13px;
    vertical-align: top;
  }}
  th {{
    background: #e9e9e9;
    text-align: left;
    position: sticky;
    top: 0;
  }}
  tr:nth-child(even) td {{ background: #fafafa; }}
  .num {{ text-align: right; font-variant-numeric: tabular-nums; }}
  .good {{ color: #0a7b28; font-weight: bold; }}
  .warn-text {{ color: #9a5b00; font-weight: bold; }}
  .badge {{
    display: inline-block;
    padding: 3px 8px;
    border-radius: 999px;
    font-size: 12px;
    font-weight: bold;
  }}
  .badge.ok {{ background: #e8f5e9; color: #1b5e20; }}
  .badge.warn {{ background: #fff3e0; color: #8a4b00; }}
  code {{ color: #b00020; white-space: pre-wrap; }}
  .footer-note {{ margin-top: 16px; font-size: 12px; color: #666; }}
  .empty {{ text-align:center; color:#666; }}
</style>
</head>
<body>
  <h1>Supabase Owner List Fields Update Report</h1>

  <div class="summary-box">
    <h2>Run Summary</h2>
    <p><strong>Mode:</strong> {escape(dry_run_note)}</p>
    <p><strong>Input folder:</strong> {escape(str(INPUT_FOLDER))}</p>
    <p><strong>Report folder:</strong> {escape(str(REPORT_FOLDER))}</p>
    <p><strong>Started:</strong> {escape(started_at.strftime('%Y-%m-%d %H:%M:%S'))}</p>
    <p><strong>Finished:</strong> {escape(ended_at.strftime('%Y-%m-%d %H:%M:%S'))}</p>
    <p><strong>Duration:</strong> {run_seconds:,.1f} seconds</p>
    <p><strong>Target tables:</strong> {escape(', '.join(TARGET_TABLES))}</p>
    <p><strong>Matching strategy:</strong> local <code>land_id/id</code> + local <code>id_list</code> matched against Supabase <code>land_id</code> and <code>id_list</code> for the same county.</p>
    <p><strong>Fields updated:</strong> acres_list, id_list, market_value_list, owner_tax_year_list, deed_date_list</p>
  </div>

  <div class="cards">
    <div class="card"><div class="label">Counties processed</div><div class="value">{totals['counties']:,}</div></div>
    <div class="card"><div class="label">Table runs</div><div class="value">{totals['table_runs']:,}</div></div>
    <div class="card"><div class="label">Source rows</div><div class="value">{totals['source_rows']:,}</div></div>
    <div class="card"><div class="label">Prepared source rows</div><div class="value good">{totals['prepared_sources']:,}</div></div>
    <div class="card"><div class="label">DB rows fetched</div><div class="value">{totals['db_rows_fetched']:,}</div></div>
    <div class="card"><div class="label">Matched sources</div><div class="value good">{totals['matched_sources']:,}</div></div>
    <div class="card"><div class="label">Proposed updates</div><div class="value good">{totals['proposed_updates']:,}</div></div>
    <div class="card"><div class="label">Applied updates</div><div class="value good">{totals['applied_updates']:,}</div></div>
    <div class="card"><div class="label">Unmatched sources</div><div class="value warn-text">{totals['unmatched_sources']:,}</div></div>
    <div class="card"><div class="label">Ambiguous skipped</div><div class="value warn-text">{totals['ambiguous_sources']:,}</div></div>
    <div class="card"><div class="label">No-change matches</div><div class="value">{totals['no_change_matches']:,}</div></div>
    <div class="card"><div class="label">Non-null market values</div><div class="value">{totals['market_values']:,}</div></div>
    <div class="card"><div class="label">Non-null tax years</div><div class="value">{totals['tax_years']:,}</div></div>
    <div class="card"><div class="label">Non-null deed dates</div><div class="value">{totals['deed_dates']:,}</div></div>
  </div>

  <h2>Per-County and Per-Table Details</h2>
  <table>
    <thead>
      <tr>
        <th>County</th>
        <th>Table</th>
        <th>Files</th>
        <th>Source Rows</th>
        <th>Prepared</th>
        <th>DB Rows</th>
        <th>Matched</th>
        <th>Unmatched</th>
        <th>Ambiguous</th>
        <th>No Change</th>
        <th>Proposed</th>
        <th>Applied</th>
        <th>id_list</th>
        <th>acres_list</th>
        <th>Market</th>
        <th>Tax Year</th>
        <th>Deed Date</th>
        <th>Status</th>
        <th>Error</th>
      </tr>
    </thead>
    <tbody>
      {rows_html}
    </tbody>
  </table>

  <h2>Field Change Breakdown</h2>
  <table>
    <thead><tr><th>Field</th><th>Rows Changed</th></tr></thead>
    <tbody>{field_html}</tbody>
  </table>

  <h2>Skipped / Review Reasons</h2>
  <table>
    <thead><tr><th>Reason</th><th>Count</th></tr></thead>
    <tbody>{skip_html}</tbody>
  </table>

  <p class="footer-note">
    The script updates existing Supabase rows only. It does not insert new owners. When existing list values are already present, they are kept by default; missing values are filled by matching parcel IDs inside id_list. Set OVERWRITE_EXISTING_VALUES=True only if you intentionally want the local pipeline file to replace existing DB values.
  </p>
</body>
</html>
"""
    REPORT_HTML_PATH.write_text(html, encoding="utf-8")
    log(f"[REPORT] HTML written: {REPORT_HTML_PATH}")


# =============================================================================
# MAIN PROCESS
# =============================================================================

def process_county(
    client: Client,
    county_folder: Path,
    county_meta: CountyMeta,
) -> Tuple[List[CountyTableReportRow], List[SkippedRow], List[ProposedUpdate]]:
    county_name = county_folder.name
    sources, source_skips, source_stats = read_and_prepare_county_sources(county_folder, county_name)

    log(
        f"[SOURCE] {county_name}: files={source_stats.get('files_read', 0):,} "
        f"rows={source_stats.get('source_rows', 0):,} prepared={len(sources):,} "
        f"skipped_source={len(source_skips):,} length_mismatch={source_stats.get('source_rows_with_length_mismatch', 0):,}"
    )

    reports: List[CountyTableReportRow] = []
    all_skips: List[SkippedRow] = list(source_skips)
    all_updates: List[ProposedUpdate] = []

    if not sources:
        for table_name in TARGET_TABLES:
            reports.append(CountyTableReportRow(
                county_name=county_name,
                table_name=table_name,
                files_read=source_stats.get("files_read", 0),
                source_rows=source_stats.get("source_rows", 0),
                prepared_sources=0,
                source_rows_missing_land_id=source_stats.get("source_rows_missing_land_id", 0),
                source_rows_without_valid_ids=source_stats.get("source_rows_without_valid_ids", 0),
                source_rows_with_length_mismatch=source_stats.get("source_rows_with_length_mismatch", 0),
                db_rows_fetched=0,
                matched_sources=0,
                unmatched_sources=0,
                ambiguous_sources=0,
                no_change_matches=0,
                duplicate_update_conflicts=0,
                proposed_updates=0,
                applied_updates=0,
                ids_added_to_db_lists=0,
                id_list_updates=0,
                acres_list_updates=0,
                market_value_updates=0,
                owner_tax_year_updates=0,
                deed_date_updates=0,
                non_null_acres=0,
                non_null_market_values=0,
                non_null_owner_tax_years=0,
                non_null_deed_dates=0,
                status="warn",
                error="no_prepared_source_rows",
            ))
        return reports, source_skips, all_updates

    for table_name in TARGET_TABLES:
        log("-" * 90)
        log(f"[TABLE] {county_name} -> {table_name}")
        report, skips, updates = process_table_for_county(
            client=client,
            county_meta=county_meta,
            county_name=county_name,
            table_name=table_name,
            sources=sources,
            source_skips=source_skips,
            source_stats=source_stats,
        )
        reports.append(report)
        all_skips.extend(skips)
        all_updates.extend(updates)

    return reports, all_skips, all_updates


def main() -> None:
    started_at = datetime.now()
    log("=" * 90)
    log("[START] Supabase owner list fields update by land_id/id_list")
    log(f"[TIME]   {now_label()}")
    log(f"[INPUT]  {INPUT_FOLDER}")
    log(f"[REPORT] {REPORT_FOLDER}")
    log(f"[MODE]   {'DRY RUN - no DB writes' if DRY_RUN else 'LIVE UPDATE'}")
    log(f"[TABLES] {', '.join(TARGET_TABLES)}")
    log(f"[FIELDS] {', '.join(UPDATE_LIST_FIELDS)}")
    log("=" * 90)

    ensure_folder(REPORT_FOLDER)

    client = get_supabase_client()
    county_meta_map = fetch_county_metadata(client)

    county_folders = list_county_folders(INPUT_FOLDER)
    log(f"[MAIN] Found {len(county_folders):,} county folder(s).")

    all_reports: List[CountyTableReportRow] = []
    all_skips: List[SkippedRow] = []
    all_updates: List[ProposedUpdate] = []

    for idx, county_folder in enumerate(county_folders, start=1):
        county_name = county_folder.name
        log("=" * 90)
        log(f"[COUNTY] ({idx:,}/{len(county_folders):,}) {county_name}")

        meta = county_meta_map.get(county_name.lower())
        if not meta:
            msg = "county_not_found_in_supabase_county_table"
            log(f"[WARN] {county_name}: {msg}. Skipping.")
            for table_name in TARGET_TABLES:
                all_reports.append(CountyTableReportRow(
                    county_name=county_name,
                    table_name=table_name,
                    files_read=0,
                    source_rows=0,
                    prepared_sources=0,
                    source_rows_missing_land_id=0,
                    source_rows_without_valid_ids=0,
                    source_rows_with_length_mismatch=0,
                    db_rows_fetched=0,
                    matched_sources=0,
                    unmatched_sources=0,
                    ambiguous_sources=0,
                    no_change_matches=0,
                    duplicate_update_conflicts=0,
                    proposed_updates=0,
                    applied_updates=0,
                    ids_added_to_db_lists=0,
                    id_list_updates=0,
                    acres_list_updates=0,
                    market_value_updates=0,
                    owner_tax_year_updates=0,
                    deed_date_updates=0,
                    non_null_acres=0,
                    non_null_market_values=0,
                    non_null_owner_tax_years=0,
                    non_null_deed_dates=0,
                    status="warn",
                    error=msg,
                ))
            continue

        try:
            reports, skips, updates = process_county(client, county_folder, meta)
            all_reports.extend(reports)
            all_skips.extend(skips)
            all_updates.extend(updates)

            county_applied = sum(r.applied_updates for r in reports)
            county_proposed = sum(r.proposed_updates for r in reports)
            county_unmatched = sum(r.unmatched_sources for r in reports)
            county_ambiguous = sum(r.ambiguous_sources for r in reports)
            log(
                f"[COUNTY DONE] {county_name}: proposed={county_proposed:,} "
                f"applied={county_applied:,} unmatched={county_unmatched:,} ambiguous={county_ambiguous:,}"
            )
        except Exception as exc:
            log(f"[ERROR] {county_name} failed: {exc}")
            log(traceback.format_exc())
            for table_name in TARGET_TABLES:
                all_reports.append(CountyTableReportRow(
                    county_name=county_name,
                    table_name=table_name,
                    files_read=0,
                    source_rows=0,
                    prepared_sources=0,
                    source_rows_missing_land_id=0,
                    source_rows_without_valid_ids=0,
                    source_rows_with_length_mismatch=0,
                    db_rows_fetched=0,
                    matched_sources=0,
                    unmatched_sources=0,
                    ambiguous_sources=0,
                    no_change_matches=0,
                    duplicate_update_conflicts=0,
                    proposed_updates=0,
                    applied_updates=0,
                    ids_added_to_db_lists=0,
                    id_list_updates=0,
                    acres_list_updates=0,
                    market_value_updates=0,
                    owner_tax_year_updates=0,
                    deed_date_updates=0,
                    non_null_acres=0,
                    non_null_market_values=0,
                    non_null_owner_tax_years=0,
                    non_null_deed_dates=0,
                    status="warn",
                    error=str(exc),
                ))

    ended_at = datetime.now()

    write_csv_reports(all_reports, all_skips, all_updates)
    generate_html_report(all_reports, all_skips, all_updates, started_at=started_at, ended_at=ended_at)

    log("=" * 90)
    log("[DONE] Supabase owner list fields update by land_id/id_list completed.")
    log(f"[MODE] {'DRY RUN - no DB writes' if DRY_RUN else 'LIVE UPDATE'}")
    log(f"[REPORT] {REPORT_HTML_PATH}")
    log(f"[SUMMARY CSV] {SUMMARY_CSV_PATH}")
    log(f"[SKIPPED CSV] {SKIPPED_ROWS_CSV_PATH}")
    log(f"[UPDATE AUDIT CSV] {UPDATE_AUDIT_CSV_PATH}")
    log("=" * 90)


if __name__ == "__main__":
    main()
