#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Pipeline final step: upsert subtracted parcel-owner rows to Supabase and update Sheet1.

Recommended script name:
    9_upsert_subtracted_parcels_to_supabase_update_sheet_report_no_arg.py

Run after:
    8_subtract_existing_supabase_parcels_no_arg.py

Purpose:
- Iterates county folders under INPUT_FOLDER. Each county folder should contain the CSV/XLSX
  files generated by the subtraction step, for example:
      step_9_subtracted_existing_supabase_parcels/Hays/Hays_subtracted_existing_parcels.csv
- Builds rows for Supabase table `unique_owner_non_enriched`.
- Generates new database `unique_id` values by continuing the existing county index:
      TX-<county_id>-<index>-1
- Upserts rows into Supabase using `unique_id` as the conflict target.
- Updates Google Sheet Sheet1 columns for the matching county row(s):
      EAP Added to DB
      All Added to DB
      All Added to DB Date
- Generates timestamped HTML and CSV reports in a dated/time-stamped report folder.

Dependencies:
    pip install pandas python-dotenv supabase gspread oauth2client openpyxl

Environment variables:
    SUPABASE_URL
    SUPABASE_SERVICE_ROLE_KEY

Optional environment overrides:
    INPUT_FOLDER
    FINAL_UPSERT_INPUT_FOLDER
    REPORT_FOLDER
    FINAL_UPSERT_REPORT_FOLDER
    DRY_RUN=true/false
    GSHEET_URL
    GSHEET_CREDENTIALS_JSON

Important notes:
- The local input `id` column is treated as Supabase `land_id`.
- The local `id_list` column is treated as Supabase `id_list` integer[].
- These array/list fields are inserted when present:
      acres_list
      id_list
      market_value_list
      owner_tax_year_list
      deed_date_list
- `legal_acreage_filled_by_script` is not inserted into the table because it is not part
  of the provided `unique_owner_non_enriched` schema. It is used only to count
  "EAP Added to DB" for the Google Sheet and reports.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from datetime import datetime
from decimal import Decimal, InvalidOperation
from html import escape
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

import ast
import json
import math
import os
import re
import time
import traceback

import pandas as pd
from dotenv import find_dotenv, load_dotenv

try:
    from supabase import Client, create_client
except Exception:  # pragma: no cover
    Client = Any  # type: ignore[misc,assignment]
    create_client = None  # type: ignore[assignment]

try:
    import gspread
    from oauth2client.service_account import ServiceAccountCredentials
except Exception:  # pragma: no cover
    gspread = None  # type: ignore[assignment]
    ServiceAccountCredentials = None  # type: ignore[assignment]


# =============================================================================
# CONFIG - EDIT THESE VARIABLES, NO CLI ARGUMENTS NEEDED
# =============================================================================

# This should be the OUTPUT_FOLDER from 8_subtract_existing_supabase_parcels_no_arg.py.
DEFAULT_INPUT_FOLDER = Path(
    r"E:\dev\projects\2025\07\15\Texas Real Estate\all_data_counties_category_1_added_test\all_parcels_including_no_acreage\step_9_subtracted_existing_supabase_parcels"
)

INPUT_FOLDER = Path(
    os.environ.get("FINAL_UPSERT_INPUT_FOLDER")
    or os.environ.get("INPUT_FOLDER")
    or DEFAULT_INPUT_FOLDER
)

# Supabase tables.
UNIQUE_OWNER_TABLE = "unique_owner_non_enriched"
COUNTY_TABLE = "county"

# Batch/retry settings.
CHUNK_SIZE = 500
RETRY_ATTEMPTS = 3
RETRY_SLEEP_SEC = 2.0
FETCH_PAGE_SIZE = 1000
PROGRESS_EVERY_ROWS = 10000

# Safety/toggles.
DRY_RUN_DEFAULT = False
DRY_RUN = str(os.environ.get("DRY_RUN", str(DRY_RUN_DEFAULT))).strip().lower() in {"1", "true", "yes", "y"}
TEST_MODE = False
TEST_ROW_LIMIT = 10
SELECTED_COUNTIES: Optional[List[str]] = None  # e.g. ["Hays", "Bastrop"]

# Google Sheet config.
GSHEET_URL = os.environ.get(
    "GSHEET_URL",
    "https://docs.google.com/spreadsheets/d/1Y7eL0lfH3B_wAl1s1ARuM3LXpGOwyScBO5cyQcGpn-8/edit?gid=0#gid=0",
)
GSHEET_CREDENTIALS_JSON = os.environ.get(
    "GSHEET_CREDENTIALS_JSON",
    "earnest-smoke-451916-b5-c2d40ca80114.json",
)
SCOPE = [
    "https://spreadsheets.google.com/feeds",
    "https://www.googleapis.com/auth/drive",
]
SHEET1_NAME = "Sheet1"
SHEET1_COUNTY_HEADER = "County"
SHEET1_EAP_ADDED_HEADER = "EAP Added to DB"
SHEET1_ALL_ADDED_HEADER = "All Added to DB"
SHEET1_ALL_ADDED_DATE_HEADER = "All Added to DB Date"

# Fallback columns based on your screenshot:
# AD = EAP Added to DB, AE = All Added to DB, AF = All Added to DB Date.
SHEET1_EAP_ADDED_FALLBACK_COL = 30
SHEET1_ALL_ADDED_FALLBACK_COL = 31
SHEET1_ALL_ADDED_DATE_FALLBACK_COL = 32

# Report folder. A YYYY-MM-DD_HHMMSS subfolder is created automatically.
REPORT_BASE_FOLDER = Path(
    os.environ.get("FINAL_UPSERT_REPORT_FOLDER")
    or os.environ.get("REPORT_FOLDER")
    or "./reports/supabase_final_subtracted_parcels_upsert"
)
RUN_TS = datetime.now()
RUN_DATE_LABEL = RUN_TS.strftime("%Y-%m-%d")
RUN_TIME_LABEL = RUN_TS.strftime("%H%M%S")
RUN_FOLDER_LABEL = RUN_TS.strftime("%Y-%m-%d_%H%M%S")
REPORT_FOLDER = REPORT_BASE_FOLDER / RUN_FOLDER_LABEL
REPORT_HTML_PATH = REPORT_FOLDER / f"final_subtracted_parcels_upsert_report_{RUN_FOLDER_LABEL}.html"
REPORT_SUMMARY_CSV_PATH = REPORT_FOLDER / f"final_subtracted_parcels_upsert_summary_{RUN_FOLDER_LABEL}.csv"
REPORT_INSERTED_AUDIT_CSV_PATH = REPORT_FOLDER / f"final_subtracted_parcels_upsert_inserted_audit_{RUN_FOLDER_LABEL}.csv"
REPORT_SKIPPED_CSV_PATH = REPORT_FOLDER / f"final_subtracted_parcels_upsert_skipped_rows_{RUN_FOLDER_LABEL}.csv"

SUPPORTED_SUFFIXES = {".csv", ".xlsx", ".xls", ".xlsm"}
CSV_READ_KWARGS = {"dtype": str, "keep_default_na": False}

# Column names expected from the final local pipeline file.
COL_ID = "id"
COL_FULL_NAME = "full_name"
COL_LEGAL_ADDRESS = "legal_address"
COL_MAILING_ADDRESS = "mailing_address"
COL_ACRES = "acres"
COL_CITY = "city"
COL_ZIP = "zip"
COL_LANDS_COUNT = "lands_count"
COL_OWNED_LANDS = "owned_lands"
COL_ACRES_LIST = "acres_list"
COL_ID_LIST = "id_list"
COL_MARKET_VALUE_LIST = "market_value_list"
COL_OWNER_TAX_YEAR_LIST = "owner_tax_year_list"
COL_DEED_DATE_LIST = "deed_date_list"
COL_LEGAL_ACREAGE_FILLED_BY_SCRIPT = "legal_acreage_filled_by_script"

REQUIRED_COLUMNS = [
    COL_ID,
    COL_FULL_NAME,
    COL_LEGAL_ADDRESS,
    COL_MAILING_ADDRESS,
    COL_ACRES,
    COL_CITY,
    COL_ZIP,
]


# =============================================================================
# DATA MODELS
# =============================================================================

@dataclass
class CountyMeta:
    county_id: int
    county_name: str
    cad_category: Optional[int]


@dataclass
class OwnerRow:
    unique_id: str
    county_id: int
    county_name: str
    land_id: Optional[str]
    full_name: Optional[str]
    legal_address: Optional[str]
    mailing_address: Optional[str]
    acres: Optional[Decimal]
    city: Optional[str]
    zip: Optional[str]
    first_name_1: Optional[str]
    last_name_1: Optional[str]
    owned_lands: int
    cad_category: Optional[int]
    acres_list: Optional[List[Optional[Decimal]]]
    id_list: Optional[List[int]]
    market_value_list: Optional[List[Optional[Decimal]]]
    owner_tax_year_list: Optional[List[Optional[int]]]
    deed_date_list: Optional[List[Optional[str]]]
    eap_true_count: int
    source_file: str
    source_row_number: int


@dataclass
class CountyReportRow:
    county_name: str
    county_id: Optional[int]
    source_files: int
    source_rows: int
    rows_attempted: int
    rows_added: int
    eap_added_to_db: int
    last_index_before: int
    max_index_after: int
    db_count_before: int
    db_count_after: int
    sheet_rows_updated: int
    status: str
    error: Optional[str] = None


# =============================================================================
# LOGGING / RETRY
# =============================================================================

def log(message: str) -> None:
    print(message, flush=True)


def _retry(fn, *args, **kwargs):
    last_exc = None
    for attempt in range(1, RETRY_ATTEMPTS + 1):
        try:
            return fn(*args, **kwargs)
        except Exception as exc:
            last_exc = exc
            log(f"[RETRY] Attempt {attempt}/{RETRY_ATTEMPTS} failed: {exc}")
            if attempt < RETRY_ATTEMPTS:
                time.sleep(RETRY_SLEEP_SEC)
    raise last_exc


# =============================================================================
# BASIC HELPERS
# =============================================================================

def ensure_folder(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def is_blank(value: Any) -> bool:
    if value is None:
        return True
    if isinstance(value, float):
        try:
            if math.isnan(value):
                return True
        except Exception:
            pass
    text = str(value).strip()
    return text == "" or text.lower() in {"nan", "none", "null", "nat"}


def clean_text(value: Any, *, max_len: Optional[int] = None) -> Optional[str]:
    if is_blank(value):
        return None
    text = re.sub(r"\s+", " ", str(value).strip())
    if max_len is not None and len(text) > max_len:
        return text[:max_len]
    return text


def normalize_name(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "", (name or "").strip().lower())


def parse_decimal(value: Any) -> Optional[Decimal]:
    if is_blank(value):
        return None
    text = str(value).strip().replace(",", "")
    if text.startswith("$"):
        text = text[1:]
    try:
        return Decimal(text)
    except (InvalidOperation, ValueError):
        return None


def parse_int(value: Any) -> Optional[int]:
    if is_blank(value):
        return None
    text = str(value).strip().replace(",", "")
    try:
        return int(Decimal(text))
    except Exception:
        return None


def parse_jsonish_list(value: Any) -> List[Any]:
    if value is None:
        return []
    if isinstance(value, list):
        return value
    if isinstance(value, tuple):
        return list(value)
    if isinstance(value, float):
        try:
            if math.isnan(value):
                return []
        except Exception:
            pass
    text = str(value).strip()
    if not text or text.lower() in {"nan", "none", "null", "nat"}:
        return []
    if text.startswith("[") and text.endswith("]"):
        try:
            parsed = json.loads(text)
            if isinstance(parsed, list):
                return parsed
        except Exception:
            pass
        try:
            parsed = ast.literal_eval(text)
            if isinstance(parsed, list):
                return parsed
        except Exception:
            pass
    if "|" in text:
        return [p.strip() for p in text.split("|")]
    return [p.strip() for p in text.split(",")]


def pad_or_trim(values: List[Any], target_len: int, pad_value: Any = None) -> List[Any]:
    if target_len <= 0:
        return []
    out = list(values[:target_len])
    while len(out) < target_len:
        out.append(pad_value)
    return out


def parse_int_list(value: Any, target_len: Optional[int] = None) -> List[Optional[int]]:
    raw_items = parse_jsonish_list(value)
    out: List[Optional[int]] = []
    for item in raw_items:
        out.append(parse_int(item))
    if target_len is not None:
        out = pad_or_trim(out, target_len, None)
    return out


def parse_decimal_list(value: Any, target_len: Optional[int] = None) -> List[Optional[Decimal]]:
    raw_items = parse_jsonish_list(value)
    out: List[Optional[Decimal]] = []
    for item in raw_items:
        out.append(parse_decimal(item))
    if target_len is not None:
        out = pad_or_trim(out, target_len, None)
    return out


def parse_date_to_iso(value: Any) -> Optional[str]:
    if is_blank(value):
        return None
    text = str(value).strip()
    # Pandas handles MM/DD/YYYY, YYYY-MM-DD, and Excel-like strings well enough here.
    dt = pd.to_datetime(text, errors="coerce")
    if pd.isna(dt):
        return None
    return dt.strftime("%Y-%m-%d")


def parse_date_list(value: Any, target_len: Optional[int] = None) -> List[Optional[str]]:
    raw_items = parse_jsonish_list(value)
    out = [parse_date_to_iso(item) for item in raw_items]
    if target_len is not None:
        out = pad_or_trim(out, target_len, None)
    return out


def parse_bool(value: Any) -> Optional[bool]:
    if is_blank(value):
        return None
    text = str(value).strip().lower()
    if text in {"true", "t", "1", "yes", "y"}:
        return True
    if text in {"false", "f", "0", "no", "n"}:
        return False
    return None


def parse_bool_list(value: Any, target_len: Optional[int] = None) -> List[Optional[bool]]:
    raw_items = parse_jsonish_list(value)
    out = [parse_bool(item) for item in raw_items]
    if target_len is not None:
        out = pad_or_trim(out, target_len, None)
    return out


def normalize_numeric_array(values: Optional[List[Optional[Decimal]]]) -> Optional[List[Optional[float]]]:
    if not values:
        return None
    return [float(v) if v is not None else None for v in values]


def normalize_int_array(values: Optional[List[Optional[int]]]) -> Optional[List[Optional[int]]]:
    if not values:
        return None
    return [int(v) if v is not None else None for v in values]


def normalize_date_array(values: Optional[List[Optional[str]]]) -> Optional[List[Optional[str]]]:
    if not values:
        return None
    return [v if v else None for v in values]


def naive_split_full_name(full_name: Optional[Any]) -> Tuple[Optional[str], Optional[str]]:
    if is_blank(full_name):
        return None, None
    text = str(full_name).strip()
    # Remove MA# prefix for grouped mailing-address rows.
    if text.upper().startswith("MA#") and "|" in text:
        text = text.split("|", 1)[1].strip()
    if "&" in text:
        text = text.split("&", 1)[0].strip()
    tokens = text.split()
    if not tokens:
        return None, None
    if len(tokens) == 1:
        return tokens[0][:100], None
    # This follows the reference script behavior: first token as last_name, rest as first_name.
    return " ".join(tokens[1:])[:100], tokens[0][:100]


# =============================================================================
# SUPABASE
# =============================================================================

def get_supabase_client(env_path: Optional[str] = None) -> Client:
    if create_client is None:
        raise RuntimeError("The 'supabase' package is not installed. Run: pip install supabase")
    if env_path is None:
        default_env = Path(__file__).resolve().parent / ".env"
        if default_env.exists():
            load_dotenv(default_env, override=False)
        else:
            load_dotenv(find_dotenv(usecwd=True), override=False)
    else:
        load_dotenv(env_path, override=False)

    url = os.getenv("SUPABASE_URL")
    key = os.getenv("SUPABASE_SERVICE_ROLE_KEY")
    if not url or not key:
        raise RuntimeError("Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in environment/.env")
    return create_client(url, key)


def fetch_county_metadata(client: Client) -> Dict[str, CountyMeta]:
    log("[META] Fetching county metadata from Supabase...")
    resp = _retry(
        client.table(COUNTY_TABLE)
        .select("county_id, county_name, cad_category")
        .execute
    )
    rows = resp.data or []
    out: Dict[str, CountyMeta] = {}
    for row in rows:
        name = clean_text(row.get("county_name"))
        if not name:
            continue
        out[normalize_name(name)] = CountyMeta(
            county_id=int(row["county_id"]),
            county_name=name,
            cad_category=row.get("cad_category"),
        )
    log(f"[META] Loaded {len(out):,} county records.")
    return out


def get_table_row_count(client: Client) -> int:
    resp = _retry(
        client.table(UNIQUE_OWNER_TABLE)
        .select("unique_id", count="exact")
        .execute
    )
    return int(resp.count or 0)


def get_count_for_county(client: Client, county_id: int) -> int:
    resp = _retry(
        client.table(UNIQUE_OWNER_TABLE)
        .select("unique_id", count="exact")
        .eq("county_id", county_id)
        .execute
    )
    return int(resp.count or 0)


def extract_index_from_unique_id(unique_id: str) -> Optional[int]:
    try:
        parts = str(unique_id).split("-")
        if len(parts) != 4:
            return None
        return int(parts[2])
    except Exception:
        return None


def get_max_index_for_county(client: Client, county_id: int) -> int:
    offset = 0
    max_index = 0
    while True:
        resp = _retry(
            client.table(UNIQUE_OWNER_TABLE)
            .select("unique_id")
            .eq("county_id", county_id)
            .range(offset, offset + FETCH_PAGE_SIZE - 1)
            .execute
        )
        rows = resp.data or []
        if not rows:
            break
        for row in rows:
            idx = extract_index_from_unique_id(row.get("unique_id", ""))
            if idx is not None and idx > max_index:
                max_index = idx
        if len(rows) < FETCH_PAGE_SIZE:
            break
        offset += FETCH_PAGE_SIZE
    return max_index


def generate_unique_id(county_id: int, index: int, version: int = 1) -> str:
    return f"TX-{county_id}-{index}-{version}"


# =============================================================================
# FILE READERS
# =============================================================================

def list_county_folders(input_folder: Path) -> List[Path]:
    if not input_folder.exists():
        raise FileNotFoundError(f"Input folder does not exist: {input_folder}")
    if not input_folder.is_dir():
        raise NotADirectoryError(f"Input path is not a folder: {input_folder}")
    folders = [p for p in input_folder.iterdir() if p.is_dir()]
    if SELECTED_COUNTIES:
        selected = {normalize_name(c) for c in SELECTED_COUNTIES}
        folders = [p for p in folders if normalize_name(p.name) in selected]
    return sorted(folders, key=lambda p: p.name)


def list_data_files(county_folder: Path) -> List[Path]:
    files = [p for p in county_folder.iterdir() if p.is_file() and p.suffix.lower() in SUPPORTED_SUFFIXES]
    # Prefer final CSVs over reports/audits if multiple files are present.
    files = [p for p in files if not p.name.lower().startswith(("summary", "audit"))]
    return sorted(files)


def read_data_file(path: Path) -> pd.DataFrame:
    suffix = path.suffix.lower()
    if suffix == ".csv":
        return pd.read_csv(path, **CSV_READ_KWARGS)
    if suffix in {".xlsx", ".xls", ".xlsm"}:
        return pd.read_excel(path, engine="openpyxl", dtype=str, keep_default_na=False)
    raise ValueError(f"Unsupported file type: {path.suffix}")


def read_county_files(county_folder: Path) -> Tuple[pd.DataFrame, int, List[str]]:
    files = list_data_files(county_folder)
    if not files:
        return pd.DataFrame(), 0, []
    dfs: List[pd.DataFrame] = []
    total_rows = 0
    file_names: List[str] = []
    for path in files:
        log(f"[FILE] Reading {county_folder.name}/{path.name}")
        df = read_data_file(path)
        df["__source_file"] = path.name
        df["__source_row_number"] = range(2, len(df) + 2)
        dfs.append(df)
        total_rows += len(df)
        file_names.append(path.name)
    full_df = pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()
    return full_df, total_rows, file_names


# =============================================================================
# ROW BUILDING
# =============================================================================

def get_lands_count(row: pd.Series, id_list: List[int]) -> int:
    for col in (COL_LANDS_COUNT, COL_OWNED_LANDS):
        if col in row.index:
            parsed = parse_int(row.get(col))
            if parsed is not None:
                return max(parsed, 0)
    return len(id_list) if id_list else 1


def build_owner_rows_for_county(
    county_folder: Path,
    county_meta: CountyMeta,
    start_index: int,
) -> Tuple[List[OwnerRow], int, List[Dict[str, Any]], List[str]]:
    df, source_rows, file_names = read_county_files(county_folder)
    skipped: List[Dict[str, Any]] = []
    if df.empty:
        return [], source_rows, skipped, file_names

    missing = [c for c in REQUIRED_COLUMNS if c not in df.columns]
    if missing:
        raise KeyError(f"Missing required columns in {county_folder.name}: {missing}")

    df = df.reset_index(drop=True)
    owner_rows: List[OwnerRow] = []

    for idx, row in df.iterrows():
        if (idx + 1) % PROGRESS_EVERY_ROWS == 0:
            log(f"[BUILD] {county_folder.name}: built {idx + 1:,}/{len(df):,} source rows...")

        land_id = clean_text(row.get(COL_ID), max_len=64)
        local_id_int = parse_int(row.get(COL_ID))

        raw_id_list = parse_int_list(row.get(COL_ID_LIST)) if COL_ID_LIST in row.index else []
        id_list = [int(v) for v in raw_id_list if v is not None]
        if not id_list and local_id_int is not None:
            id_list = [local_id_int]

        if not land_id and id_list:
            land_id = str(id_list[0])

        if not land_id and not id_list:
            skipped.append({
                "county_name": county_folder.name,
                "source_file": row.get("__source_file"),
                "source_row_number": row.get("__source_row_number"),
                "reason": "missing_id_and_id_list",
            })
            continue

        target_len = len(id_list) if id_list else 1
        acres_list = parse_decimal_list(row.get(COL_ACRES_LIST), target_len=target_len) if COL_ACRES_LIST in row.index else []
        if not any(v is not None for v in acres_list):
            acres_val = parse_decimal(row.get(COL_ACRES))
            acres_list = [acres_val] if target_len == 1 else pad_or_trim([acres_val], target_len, None)

        market_value_list = parse_decimal_list(row.get(COL_MARKET_VALUE_LIST), target_len=target_len) if COL_MARKET_VALUE_LIST in row.index else None
        owner_tax_year_list = parse_int_list(row.get(COL_OWNER_TAX_YEAR_LIST), target_len=target_len) if COL_OWNER_TAX_YEAR_LIST in row.index else None
        deed_date_list = parse_date_list(row.get(COL_DEED_DATE_LIST), target_len=target_len) if COL_DEED_DATE_LIST in row.index else None
        eap_flags = parse_bool_list(row.get(COL_LEGAL_ACREAGE_FILLED_BY_SCRIPT), target_len=target_len) if COL_LEGAL_ACREAGE_FILLED_BY_SCRIPT in row.index else []
        eap_true_count = sum(1 for flag in eap_flags if flag is True)

        full_name = clean_text(row.get(COL_FULL_NAME), max_len=150)
        legal_address = clean_text(row.get(COL_LEGAL_ADDRESS))
        mailing_address = clean_text(row.get(COL_MAILING_ADDRESS))
        acres = parse_decimal(row.get(COL_ACRES))
        city = clean_text(row.get(COL_CITY), max_len=100)
        zip_code = clean_text(row.get(COL_ZIP), max_len=10)
        first_name_1, last_name_1 = naive_split_full_name(full_name)
        owned_lands = get_lands_count(row, id_list)
        row_index = start_index + len(owner_rows) + 1
        unique_id = generate_unique_id(county_meta.county_id, row_index, version=1)

        owner_rows.append(
            OwnerRow(
                unique_id=unique_id,
                county_id=county_meta.county_id,
                county_name=county_meta.county_name,
                land_id=land_id,
                full_name=full_name,
                legal_address=legal_address,
                mailing_address=mailing_address,
                acres=acres,
                city=city,
                zip=zip_code,
                first_name_1=first_name_1,
                last_name_1=last_name_1,
                owned_lands=owned_lands,
                cad_category=county_meta.cad_category,
                acres_list=acres_list,
                id_list=id_list or None,
                market_value_list=market_value_list,
                owner_tax_year_list=owner_tax_year_list,
                deed_date_list=deed_date_list,
                eap_true_count=eap_true_count,
                source_file=str(row.get("__source_file") or ""),
                source_row_number=parse_int(row.get("__source_row_number")) or 0,
            )
        )

    return owner_rows, source_rows, skipped, file_names


# =============================================================================
# DB UPSERT
# =============================================================================

def owner_row_to_payload(row: OwnerRow) -> Dict[str, Any]:
    return {
        "unique_id": row.unique_id,
        "county_id": row.county_id,
        "county_name": row.county_name,
        "land_id": row.land_id,
        "full_name": row.full_name,
        "legal_address": row.legal_address,
        "mailing_address": row.mailing_address,
        "acres": float(row.acres) if row.acres is not None else None,
        "city": row.city,
        "zip": row.zip,
        "first_name_1": row.first_name_1,
        "last_name_1": row.last_name_1,
        "owned_lands": int(row.owned_lands or 0),
        "cad_category": row.cad_category,
        "acres_list": normalize_numeric_array(row.acres_list),
        "id_list": row.id_list if row.id_list else None,
        "market_value_list": normalize_numeric_array(row.market_value_list),
        "owner_tax_year_list": normalize_int_array(row.owner_tax_year_list),
        "deed_date_list": normalize_date_array(row.deed_date_list),
    }


def upsert_owner_rows(client: Client, rows: List[OwnerRow]) -> int:
    if not rows:
        return 0
    payloads = [owner_row_to_payload(row) for row in rows]
    affected_total = 0
    for i in range(0, len(payloads), CHUNK_SIZE):
        chunk = payloads[i:i + CHUNK_SIZE]
        log(f"[DB] Upserting rows {i + 1:,}-{i + len(chunk):,} / {len(payloads):,}")
        resp = _retry(
            client.table(UNIQUE_OWNER_TABLE)
            .upsert(chunk, on_conflict="unique_id")
            .execute
        )
        affected_total += len(resp.data or [])
    return affected_total


# =============================================================================
# GOOGLE SHEETS
# =============================================================================

def get_gspread_client(credentials_json_file: str, scope: List[str]):
    if gspread is None or ServiceAccountCredentials is None:
        raise RuntimeError("Google Sheets packages are missing. Run: pip install gspread oauth2client")
    creds_path = Path(credentials_json_file)
    if not creds_path.exists():
        alt = Path(__file__).resolve().parent / credentials_json_file
        if alt.exists():
            creds_path = alt
    creds = ServiceAccountCredentials.from_json_keyfile_name(str(creds_path), scope)
    return gspread.authorize(creds)


def open_worksheet(client, gsheet_url: str, worksheet_name: str):
    spreadsheet = client.open_by_url(gsheet_url)
    return spreadsheet.worksheet(worksheet_name)


def header_map(headers: Sequence[str]) -> Dict[str, int]:
    return {str(h).strip(): i + 1 for i, h in enumerate(headers) if str(h).strip()}


def build_sheet1_index(ws) -> Tuple[Dict[str, List[int]], Dict[str, int]]:
    values = ws.get_all_values()
    if not values or len(values) < 2:
        raise ValueError("Sheet1 is empty or has no data rows.")
    headers = values[0]
    hmap = header_map(headers)
    county_col = hmap.get(SHEET1_COUNTY_HEADER)
    if not county_col:
        raise ValueError(f'Sheet1 missing header "{SHEET1_COUNTY_HEADER}"')

    county_to_rows: Dict[str, List[int]] = {}
    for row_num in range(2, len(values) + 1):
        row = values[row_num - 1]
        county_val = row[county_col - 1].strip() if len(row) >= county_col else ""
        if county_val:
            county_to_rows.setdefault(normalize_name(county_val), []).append(row_num)
    return county_to_rows, hmap


def get_sheet_col(hmap: Dict[str, int], header_name: str, fallback_col: int) -> int:
    return hmap.get(header_name, fallback_col)


def update_sheet1_final_db_columns(
    ws,
    sheet_index: Dict[str, List[int]],
    hmap: Dict[str, int],
    county_name: str,
    eap_added_to_db: int,
    all_added_to_db: int,
    run_date: str,
) -> int:
    key = normalize_name(county_name)
    target_rows = sheet_index.get(key) or []
    if not target_rows:
        return 0

    eap_col = get_sheet_col(hmap, SHEET1_EAP_ADDED_HEADER, SHEET1_EAP_ADDED_FALLBACK_COL)
    all_col = get_sheet_col(hmap, SHEET1_ALL_ADDED_HEADER, SHEET1_ALL_ADDED_FALLBACK_COL)
    date_col = get_sheet_col(hmap, SHEET1_ALL_ADDED_DATE_HEADER, SHEET1_ALL_ADDED_DATE_FALLBACK_COL)

    updates = []
    for row_num in target_rows:
        updates.extend([
            {"range": gspread.utils.rowcol_to_a1(row_num, eap_col), "values": [[eap_added_to_db]]},
            {"range": gspread.utils.rowcol_to_a1(row_num, all_col), "values": [[all_added_to_db]]},
            {"range": gspread.utils.rowcol_to_a1(row_num, date_col), "values": [[run_date]]},
        ])
    ws.batch_update(updates)
    return len(target_rows)


# =============================================================================
# REPORTS
# =============================================================================

def write_csv_report(path: Path, rows: List[Dict[str, Any]]) -> None:
    ensure_folder(path.parent)
    pd.DataFrame(rows).to_csv(path, index=False, encoding="utf-8-sig")
    log(f"[REPORT] CSV written: {path}")


def build_inserted_audit_rows(rows: List[OwnerRow]) -> List[Dict[str, Any]]:
    audit: List[Dict[str, Any]] = []
    for row in rows:
        audit.append({
            "county_name": row.county_name,
            "unique_id": row.unique_id,
            "land_id": row.land_id,
            "full_name": row.full_name,
            "acres": float(row.acres) if row.acres is not None else None,
            "owned_lands": row.owned_lands,
            "id_list_count": len(row.id_list or []),
            "eap_true_count": row.eap_true_count,
            "source_file": row.source_file,
            "source_row_number": row.source_row_number,
        })
    return audit


def generate_html_report(
    output_path: Path,
    table_rows_before: int,
    table_rows_after: int,
    county_reports: List[CountyReportRow],
    skipped_rows: List[Dict[str, Any]],
) -> None:
    ensure_folder(output_path.parent)
    timestamp = RUN_TS.strftime("%Y-%m-%d %H:%M:%S")
    total_source_rows = sum(r.source_rows for r in county_reports)
    total_attempted = sum(r.rows_attempted for r in county_reports)
    total_added = sum(r.rows_added for r in county_reports)
    total_eap = sum(r.eap_added_to_db for r in county_reports)
    total_sheet_updates = sum(r.sheet_rows_updated for r in county_reports)
    mode_label = "DRY RUN - no DB or Google Sheet writes" if DRY_RUN else "LIVE RUN"

    rows_html = []
    for row in county_reports:
        status_class = "good" if row.status == "ok" else "warn-text"
        error_html = f"<code>{escape(row.error or '')}</code>" if row.error else ""
        rows_html.append(
            "<tr>"
            f"<td>{escape(row.county_name)}</td>"
            f"<td class='num'>{row.source_files:,}</td>"
            f"<td class='num'>{row.source_rows:,}</td>"
            f"<td class='num'>{row.rows_attempted:,}</td>"
            f"<td class='num good'>{row.rows_added:,}</td>"
            f"<td class='num good'>{row.eap_added_to_db:,}</td>"
            f"<td class='num'>{row.db_count_before:,}</td>"
            f"<td class='num'>{row.db_count_after:,}</td>"
            f"<td class='num'>{row.last_index_before:,}</td>"
            f"<td class='num'>{row.max_index_after:,}</td>"
            f"<td class='num'>{row.sheet_rows_updated:,}</td>"
            f"<td class='{status_class}'>{escape(row.status)}</td>"
            f"<td>{error_html}</td>"
            "</tr>"
        )
    rows_block = "\n".join(rows_html) if rows_html else "<tr><td colspan='13'>No counties processed.</td></tr>"

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Final Supabase Upsert Report</title>
<style>
  body {{ background-color: #f0f0f0; font-family: Arial, sans-serif; padding: 20px; color: #222; }}
  h1, h2 {{ color: #333; }}
  .summary-box {{ background: #fff; border-radius: 8px; padding: 16px; margin-bottom: 18px; box-shadow: 0 1px 3px rgba(0,0,0,0.12); font-size: 14px; }}
  .cards {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(210px, 1fr)); gap: 12px; margin: 14px 0; }}
  .card {{ background: #fff; border-radius: 8px; padding: 14px; box-shadow: 0 1px 3px rgba(0,0,0,0.12); }}
  .card .label {{ color: #666; font-size: 12px; text-transform: uppercase; letter-spacing: .03em; }}
  .card .value {{ margin-top: 6px; font-size: 24px; font-weight: bold; }}
  table {{ width: 100%; border-collapse: collapse; background: #fff; box-shadow: 0 1px 3px rgba(0,0,0,0.12); margin-bottom: 20px; }}
  th, td {{ padding: 8px 10px; border-bottom: 1px solid #e2e2e2; font-size: 13px; vertical-align: top; }}
  th {{ background: #e9e9e9; text-align: left; position: sticky; top: 0; }}
  tr:nth-child(even) td {{ background: #fafafa; }}
  .num {{ text-align: right; font-variant-numeric: tabular-nums; }}
  .good {{ color: #0a7b28; font-weight: bold; }}
  .warn-text {{ color: #9a5b00; font-weight: bold; }}
  code {{ color: #8a1c1c; }}
  .footer-note {{ margin-top: 16px; font-size: 12px; color: #666; }}
</style>
</head>
<body>
  <h1>Final Supabase Upsert Report</h1>
  <div class="summary-box">
    <h2>Run Summary</h2>
    <p><strong>Run time:</strong> {escape(timestamp)}</p>
    <p><strong>Mode:</strong> {escape(mode_label)}</p>
    <p><strong>Input folder:</strong> {escape(str(INPUT_FOLDER))}</p>
    <p><strong>Target table:</strong> {escape(UNIQUE_OWNER_TABLE)}</p>
    <p><strong>Google Sheet columns updated:</strong> {escape(SHEET1_EAP_ADDED_HEADER)}, {escape(SHEET1_ALL_ADDED_HEADER)}, {escape(SHEET1_ALL_ADDED_DATE_HEADER)}</p>
  </div>

  <div class="cards">
    <div class="card"><div class="label">Source Rows</div><div class="value">{total_source_rows:,}</div></div>
    <div class="card"><div class="label">Rows Attempted</div><div class="value">{total_attempted:,}</div></div>
    <div class="card"><div class="label">Rows Added</div><div class="value good">{total_added:,}</div></div>
    <div class="card"><div class="label">EAP Added to DB</div><div class="value good">{total_eap:,}</div></div>
    <div class="card"><div class="label">Table Before</div><div class="value">{table_rows_before:,}</div></div>
    <div class="card"><div class="label">Table After</div><div class="value">{table_rows_after:,}</div></div>
    <div class="card"><div class="label">Sheet Rows Updated</div><div class="value">{total_sheet_updates:,}</div></div>
    <div class="card"><div class="label">Skipped Rows</div><div class="value">{len(skipped_rows):,}</div></div>
  </div>

  <h2>Per-County Details</h2>
  <table>
    <thead>
      <tr>
        <th>County</th>
        <th>Files</th>
        <th>Source Rows</th>
        <th>Rows Attempted</th>
        <th>Rows Added</th>
        <th>EAP Added</th>
        <th>DB Count Before</th>
        <th>DB Count After</th>
        <th>Last Index Before</th>
        <th>Max Index After</th>
        <th>Sheet Rows Updated</th>
        <th>Status</th>
        <th>Error</th>
      </tr>
    </thead>
    <tbody>{rows_block}</tbody>
  </table>

  <p class="footer-note">
    EAP Added to DB is counted from TRUE values in the local legal_acreage_filled_by_script aligned list for the rows inserted in this run.
    All Added to DB is the number of database rows added for that county in this run.
  </p>
</body>
</html>
"""
    output_path.write_text(html, encoding="utf-8")
    log(f"[REPORT] HTML written: {output_path}")


# =============================================================================
# MAIN
# =============================================================================

def main() -> None:
    ensure_folder(REPORT_FOLDER)
    log("=" * 90)
    log("[START] Final upsert of subtracted parcel-owner rows to Supabase")
    log(f"[TIME]   {RUN_TS.strftime('%Y-%m-%d %H:%M:%S')}")
    log(f"[INPUT]  {INPUT_FOLDER}")
    log(f"[REPORT] {REPORT_FOLDER}")
    log(f"[MODE]   {'DRY RUN' if DRY_RUN else 'LIVE RUN'}")
    log(f"[DB]     {UNIQUE_OWNER_TABLE}")
    log("=" * 90)

    client = get_supabase_client()
    county_meta_map = fetch_county_metadata(client)

    log("[GSHEET] Opening Sheet1...")
    sheet1_ws = None
    sheet_index: Dict[str, List[int]] = {}
    sheet_hmap: Dict[str, int] = {}
    if DRY_RUN:
        log("[GSHEET] Dry run enabled: Sheet1 will not be updated.")
    else:
        gclient = get_gspread_client(GSHEET_CREDENTIALS_JSON, SCOPE)
        sheet1_ws = open_worksheet(gclient, GSHEET_URL, SHEET1_NAME)
        sheet_index, sheet_hmap = build_sheet1_index(sheet1_ws)
        log(f"[GSHEET] Loaded Sheet1 index for {len(sheet_index):,} county names.")

    table_rows_before = get_table_row_count(client)
    log(f"[DB] Table rows before run: {table_rows_before:,}")

    county_folders = list_county_folders(INPUT_FOLDER)
    log(f"[MAIN] Found {len(county_folders):,} county folder(s).")

    county_reports: List[CountyReportRow] = []
    skipped_rows_all: List[Dict[str, Any]] = []
    inserted_audit_all: List[Dict[str, Any]] = []
    rows_remaining_for_test = TEST_ROW_LIMIT if TEST_MODE else None

    for county_idx, county_folder in enumerate(county_folders, start=1):
        county_name = county_folder.name
        log("=" * 90)
        log(f"[COUNTY] ({county_idx}/{len(county_folders)}) {county_name}")
        meta = county_meta_map.get(normalize_name(county_name))
        if not meta:
            error = "county_not_found_in_supabase_county_table"
            log(f"[WARN] {county_name}: {error}")
            county_reports.append(CountyReportRow(
                county_name=county_name,
                county_id=None,
                source_files=0,
                source_rows=0,
                rows_attempted=0,
                rows_added=0,
                eap_added_to_db=0,
                last_index_before=0,
                max_index_after=0,
                db_count_before=0,
                db_count_after=0,
                sheet_rows_updated=0,
                status="warn",
                error=error,
            ))
            continue

        try:
            db_count_before = get_count_for_county(client, meta.county_id)
            last_index = get_max_index_for_county(client, meta.county_id)
            log(f"[DB] county_id={meta.county_id} rows_before={db_count_before:,} last_index={last_index:,}")

            owner_rows, source_rows, skipped_rows, file_names = build_owner_rows_for_county(
                county_folder,
                meta,
                start_index=last_index,
            )
            skipped_rows_all.extend(skipped_rows)
            log(f"[BUILD] source_rows={source_rows:,} valid_rows={len(owner_rows):,} skipped_rows={len(skipped_rows):,}")

            if TEST_MODE and owner_rows:
                if rows_remaining_for_test is None or rows_remaining_for_test <= 0:
                    log("[TEST] Reached TEST_ROW_LIMIT. Skipping remaining counties.")
                    break
                if len(owner_rows) > rows_remaining_for_test:
                    log(f"[TEST] Truncating rows from {len(owner_rows):,} to {rows_remaining_for_test:,}")
                    owner_rows = owner_rows[:rows_remaining_for_test]
                rows_remaining_for_test -= len(owner_rows)

            eap_added_count = sum(row.eap_true_count for row in owner_rows)
            affected = 0
            if owner_rows and not DRY_RUN:
                affected = upsert_owner_rows(client, owner_rows)
                log(f"[DB] Upsert complete. attempted={len(owner_rows):,} affected_response_rows={affected:,}")
            elif owner_rows:
                log(f"[DRY RUN] Would upsert {len(owner_rows):,} row(s).")
            else:
                log("[MAIN] No valid rows to upsert for this county.")

            db_count_after = get_count_for_county(client, meta.county_id) if not DRY_RUN else db_count_before
            rows_added = len(owner_rows) if DRY_RUN else max(db_count_after - db_count_before, 0)
            max_index_after = get_max_index_for_county(client, meta.county_id) if not DRY_RUN else last_index + len(owner_rows)

            sheet_rows_updated = 0
            if not DRY_RUN and sheet1_ws is not None:
                sheet_rows_updated = update_sheet1_final_db_columns(
                    sheet1_ws,
                    sheet_index,
                    sheet_hmap,
                    county_name=meta.county_name,
                    eap_added_to_db=eap_added_count,
                    all_added_to_db=rows_added,
                    run_date=RUN_TS.strftime("%Y-%m-%d"),
                )
                log(
                    f"[GSHEET] Updated {sheet_rows_updated:,} Sheet1 row(s): "
                    f"EAP Added to DB={eap_added_count:,}, All Added to DB={rows_added:,}, "
                    f"All Added to DB Date={RUN_TS.strftime('%Y-%m-%d')}"
                )
            elif DRY_RUN:
                log(
                    f"[DRY RUN] Would update Sheet1: EAP Added to DB={eap_added_count:,}, "
                    f"All Added to DB={rows_added:,}, All Added to DB Date={RUN_TS.strftime('%Y-%m-%d')}"
                )

            inserted_audit_all.extend(build_inserted_audit_rows(owner_rows))
            county_reports.append(CountyReportRow(
                county_name=meta.county_name,
                county_id=meta.county_id,
                source_files=len(file_names),
                source_rows=source_rows,
                rows_attempted=len(owner_rows),
                rows_added=rows_added,
                eap_added_to_db=eap_added_count,
                last_index_before=last_index,
                max_index_after=max_index_after,
                db_count_before=db_count_before,
                db_count_after=db_count_after,
                sheet_rows_updated=sheet_rows_updated,
                status="ok",
                error=None,
            ))
            log(f"[DONE] {county_name}: added={rows_added:,}, eap_added={eap_added_count:,}")

        except Exception as exc:
            err = f"{type(exc).__name__}: {exc}"
            log(f"[ERROR] {county_name}: {err}")
            traceback.print_exc()
            county_reports.append(CountyReportRow(
                county_name=county_name,
                county_id=meta.county_id,
                source_files=0,
                source_rows=0,
                rows_attempted=0,
                rows_added=0,
                eap_added_to_db=0,
                last_index_before=0,
                max_index_after=0,
                db_count_before=0,
                db_count_after=0,
                sheet_rows_updated=0,
                status="error",
                error=err,
            ))

    table_rows_after = get_table_row_count(client) if not DRY_RUN else table_rows_before

    summary_rows = [asdict(row) for row in county_reports]
    write_csv_report(REPORT_SUMMARY_CSV_PATH, summary_rows)
    write_csv_report(REPORT_INSERTED_AUDIT_CSV_PATH, inserted_audit_all)
    write_csv_report(REPORT_SKIPPED_CSV_PATH, skipped_rows_all)
    generate_html_report(REPORT_HTML_PATH, table_rows_before, table_rows_after, county_reports, skipped_rows_all)

    total_added = sum(row.rows_added for row in county_reports)
    total_eap = sum(row.eap_added_to_db for row in county_reports)
    log("=" * 90)
    log("[DONE] Final Supabase upsert pipeline completed.")
    log(f"Counties processed : {len(county_reports):,}")
    log(f"Rows added         : {total_added:,}")
    log(f"EAP added to DB    : {total_eap:,}")
    log(f"Skipped rows       : {len(skipped_rows_all):,}")
    log(f"Report folder      : {REPORT_FOLDER}")
    log("=" * 90)


if __name__ == "__main__":
    main()
